# Evaluate Term Dispersion Scores on the GENIA Corpus Data and Reproduce Results Reported in the Mannuscript 

Authors: Samuel Sarria Hurtado, Uyen "Rachel" Lai, and Paul Sheridan

Last update: 2025-06-03

Description: Evaluate the following term dispersion scores on the Genia corpus data:
- Inverse Document Frequency (IDF)
- Inverse Collection Frequency (ICF)
- Chi-square
- Church and Gale (CG)
- Irvine and Callison-Burch (ICB)
- Derivation of Proportions (DoP)
- Residual ICF (RICF)

Calculate average P@k scores for each scoring function using the GENIA terms as ground truth. Also, evaluate scoring functions for their ability to filter out stopwords.

## Preliminaries

In [1]:
# Imports
import sys
import json
import pandas as pd
sys.path.append('../0-base-functions/')
import wordstats
from sklearn.feature_extraction.text import CountVectorizer
import random
import numpy as np
import scipy
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from io import StringIO
from numpy import nan
from tqdm import tqdm
import rbo

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/pasheridan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

## Load the GENIA Corpus Data

In particular, we load the
- preprocessed GENIA corpus documents,
- and gold standard biological terms (i.e., lexical units) and their associated semantic classes (i.e., sems).

In [2]:
# Load the preprocessed GENIA corpus documents
genia_corpus_path = '../1-preprocessing/GENIAcorpus3.02-preprocessed.json'

with open(genia_corpus_path, "r") as j:
  genia_corpus = json.loads(j.read())

# Load gold standard terms 
genia_keywords_path = '../1-preprocessing/GENIAcorpus3.02-keywords.tsv'

with open(genia_keywords_path, "r") as c:
  genia_lexical_units_and_sems = pd.read_csv(c, sep='\t')

genia_lexical_units = genia_lexical_units_and_sems.lex.to_numpy()

## Prepare the GENIA Corpus Data for Analysis

Prepare the corpus vocabulary.

In [3]:
# Compile the GENIA corpus vocabulary
pre_vocab = []
for i in range(len(genia_corpus)):
  pre_vocab.append(genia_corpus[i].split())

vocab = []
for i in range(len(pre_vocab)):
  for j in range(len(pre_vocab[i])):
    vocab.append(pre_vocab[i][j])

vocab = list(set(vocab))
vocab.sort()

Convert GENIA documents into term-in-document matrix of token counts.

In [4]:
# Helper function to ensure that CountVectorizer doesn't ignore any terms
def analyzer_custom(doc):
  return doc.split()

# Generate term-in-document counts
counter = CountVectorizer(lowercase=False, vocabulary=vocab, analyzer=analyzer_custom)
collection = counter.transform(genia_corpus)

## Evaluate Term Dispersion Scores for Selected Measures

Calculate bag-of-words model word statistics and related quantities.

In [5]:
# Calculate word statistics and related quantities
m = len(counter.get_feature_names_out()) # vocab size
d = collection.shape[0] # collection size
N_i = wordstats.get_Ni(collection)
N_j = wordstats.get_Nj(collection)
N = wordstats.get_N(N_j)
B_ij = wordstats.get_Bij(collection)
B_i = wordstats.get_Bi(B_ij)
B_j = wordstats.get_Bj(B_ij)
DF = wordstats.get_DF(B_i, d)
CF = wordstats.get_CF(N_i)
nij_by_nj = wordstats.get_nij_by_nj(collection, N_j)
thetas = np.array(range(1, max(N_i.A[0]) + 1))/N
opt_thetas = wordstats.get_opt_thetas(N, m, d, N_i, N_j, B_i, thetas)

Evaluate word dispersion scores.

In [6]:
# Calculate word dispersion scores according the various measures used in this study
IDF = wordstats.get_IDF(DF)
ICF = wordstats.get_ICF(CF)
Chisq = wordstats.get_Chisq(collection)
CG = wordstats.get_CG(N_i, B_i)
ICB = wordstats.get_ICB(nij_by_nj, B_i)
DoP = wordstats.get_DoP(collection, N_i, N_j, N)
RICF = wordstats.get_RICF(opt_thetas, N, ICF)

/Users/pasheridan/Desktop/github-repos/bursty-term-measure/genia/3-tables/../0-base-functions/wordstats.py:209: RuntimeWarning: divide by zero encountered in log
  return -np.log(chisq_values)

Arrange term dispersion scores into a data frame.

In [7]:
# Initialize bursty scores data frame
term_scores_df = pd.DataFrame(data=
                         {'term': counter.get_feature_names_out(),
                          'IDF': IDF.A[0],
                          'ICF': ICF.A[0],
                          'Chi-sq': Chisq,
                          'CG': CG.A[0],
                          'ICB': ICB.A[0],
                          'DoP': DoP.A[0],
                          'RICF': RICF.A[0]})

In [8]:
# Print term dispersion scores to console
display(term_scores_df)

,term,IDF,ICF,Chi-sq,CG,ICB,DoP,RICF
0,'aged'_lymphocyte_lex,7.600902,12.800954,0.701595,1.0,244.0,-0.000673,-0.000251
1,'converted'_TCEd_motif_lex,7.600902,12.800954,0.701595,1.0,195.0,-0.000538,-0.000251
2,'latency_I'_lex,7.600902,12.800954,0.701595,1.0,206.0,-0.000568,-0.000251
3,'latency_II'_lex,7.600902,12.800954,0.701595,1.0,206.0,-0.000568,-0.000251
4,'master_regulator_lex,7.600902,12.800954,0.701595,1.0,63.0,-0.000174,-0.000251
...,...,...,...,...,...,...,...,...
40799,zymogen_plasma_factor_X_lex,7.600902,12.800954,0.701595,1.0,355.0,-0.000979,-0.000251
40800,zymogen_plasma_factors_VII_lex,7.600902,12.800954,0.701595,1.0,355.0,-0.000979,-0.000251
40801,zymography_lex,7.600902,12.800954,0.701595,1.0,191.0,-0.000527,-0.000251
40802,zymosan-treated_cell_lex,7.600902,12.800954,0.701595,1.0,225.0,-0.000621,-0.000251
40803,zymosan_lex,6.907755,11.414659,587.746183,2.0,458.0,-0.001285,0.692615

In [8]:
# Write to TSV
term_scores_df.to_csv('term-dispersion-scores.tsv', sep='\t')

## Compile GENIA Corpus Summary Statistics

This is the result of Table 3 from the manuscript.

In [10]:
# Collect lexical units belonging to a given high-level semantic class
def get_high_level_semantic_class_words(high_level_class_lst):
  words = []
  for k, v in lex_sem_dct.items():
    if v in high_level_class_lst:
      words.append(k)
  return words

In [30]:
# Hardcode the semantic classes according to their high-level designations.
amino_acid_sems = ['G#amino_acid_monomer', 'G#peptide', 'G#protein_N/A',
              'G#protein_complex', 'G#protein_domain_or_region',
              'G#protein_family_or_group', 'G#protein_molecule',
              'G#protein_substructure', 'G#protein_subunit',
              'G#other_organic_compound', 'G#organic', 'G#inorganic', 'G#atom',
              'G#carbohydrate', 'G#lipid']
nucleotide_sems = ['G#nucleotide', 'G#polynucleotide', 'G#DNA_N/A',
        'G#DNA_domain_or_region', 'G#DNA_family_or_group', 'G#DNA_molecule',
        'G#DNA_substructure', 'G#RNA_N/A', 'G#RNA_domain_or_region',
        'G#RNA_family_or_group', 'G#RNA_molecule', 'G#RNA_substructure']
multi_cell_sems = ['G#virus', 'G#mono_cell', 'G#multi_cell', 'G#body_part', 'G#tissue']
cell_sems = ['G#cell_type', 'G#cell_component', 'G#cell_line', 'G#other_artificial_source']
other_sems = ['G#other_name']
high_level_semantic_class_names = ['amino_acid', 'nucleotide', 'multi_cell', 'cell', 'other']
high_level_semantic_class_lex_units = [genia_lexical_units, amino_acid_sems, nucleotide_sems, multi_cell_sems, cell_sems, other_sems]

# Create dictionary of lexical units and their associated semantic classes
sem = np.array(genia_lexical_units_and_sems['sem'])
lex = np.array(genia_lexical_units_and_sems['lex'])
lex_sem_dct = dict(zip(lex, sem))

# Count number of semantic classes in each high-level class
sub_class = [len(amino_acid_sems), len(nucleotide_sems), len(multi_cell_sems), len(cell_sems), len(other_sems)]

# Count number of distinct lexical units in each high-level semantic class
amino_acid = get_high_level_semantic_class_words(amino_acid_sems)
nucleotide = get_high_level_semantic_class_words(nucleotide_sems)
multi_cell = get_high_level_semantic_class_words(multi_cell_sems)
cell = get_high_level_semantic_class_words(cell_sems)
other = get_high_level_semantic_class_words(other_sems)

# Count number of lexical units used as annotations for each high-level semantic class
high_level_class_words = [genia_lexical_units, amino_acid, nucleotide, multi_cell, cell, other]
high_level_class_words_counter = [0, 0, 0, 0, 0, 0]
for i in range(len(high_level_class_words)):
  for j in range(len(vocab)):
    if vocab[j] in high_level_class_words[i]:
      high_level_class_words_counter[i] += N_i.A[0][j]

# Create dictionary of lexical units and their associated semantic classes
sem = np.array(genia_lexical_units_and_sems['sem'])
lex = np.array(genia_lexical_units_and_sems['lex'])
lex_sem_dct = dict(zip(lex, sem))

# Count number of semantic subclasses in each high-level class
subclass_counts = [len(amino_acid_sems), len(nucleotide_sems), len(multi_cell_sems), len(cell_sems), len(other_sems)]

# Gather distinct lexical units for each high-level semantic class
amino_acid = get_high_level_semantic_class_words(amino_acid_sems)
nucleotide = get_high_level_semantic_class_words(nucleotide_sems)
multi_cell = get_high_level_semantic_class_words(multi_cell_sems)
cell = get_high_level_semantic_class_words(cell_sems)
other = get_high_level_semantic_class_words(other_sems)

# Count number of lexical units used as annotations for each high-level semantic class
lex_by_semamtic_class_counts = [0, 0, 0, 0, 0, 0]
for i in range(len(high_level_semantic_class_names)):
  for j in range(len(vocab)):
    if vocab[j] in high_level_semantic_class_names[i]:
      lex_by_semamtic_class_counts[i] += N_i.A[0][j]

# Define the data
high_level_semantic_classes = ['all', 'amino_acid', 'nucleotide', 'multi_cell', 'cell', 'other']
annotations_count_zip = zip(high_level_semantic_classes, high_level_class_words_counter)
annotations_dict = dict(annotations_count_zip)
lex_unit_counts = [len(amino_acid), len(nucleotide), len(multi_cell), len(cell), len(other)]
subclass_counts = [len(amino_acid_sems), len(nucleotide_sems), len(multi_cell_sems), len(cell_sems), len(other_sems)]
annotations = [
    annotations_dict['amino_acid'],
    annotations_dict['nucleotide'],
    annotations_dict['multi_cell'],
    annotations_dict['cell'],
    annotations_dict['other']]

# Create a data frame
genia_summary_stats_df = pd.DataFrame({
    'Semantic class': ['amino_acid', 'nucleotide', 'multi_cell', 'cell', 'other'],
    'Sub-class': subclass_counts,
    'Unique terms': lex_unit_counts,
    "Annotations": annotations
})

In [31]:
# Print GENIA summary statistics
display(genia_summary_stats_df)

  Semantic class  Sub-class  Unique terms  Annotations
0     amino_acid         15         10155        42478
1     nucleotide         12          5574        11619
2     multi_cell          5          1444         5247
3           cell          4          4051        11626
4          other          1         10560        19999

In [13]:
# Write to CSV
genia_summary_stats_df.to_csv('table-3/table-3.csv', index=False)

## Terminology Extraction Task Experiment

Here we reproduce the result of Table 4 from the manuscript.

In [18]:
def top_k(dct, k):
  keys = dct.keys()
  values = []
  for key in keys:
    values.append(dct[key][:k])
  keys_values_pair = zip(keys, values)
  return dict(keys_values_pair)
    
def resort(term_scores_df):
    sorted_terms = []
    bursty_measure_names = term_scores_df.columns.values.tolist()[1:]

    for measure in bursty_measure_names:
        # Copy the data frame and add a random column
        temp_df = term_scores_df.copy()
        temp_df['random'] = np.random.rand(len(temp_df))
        
        # Sort by the measure and the random column
        sorted_df = temp_df[['term', measure, 'random']].sort_values(by=[measure, 'random'], ascending=[False, True])
        
        # Append the sorted terms to the list
        sorted_terms.append(np.array(sorted_df['term']))
        
        # Drop the random column from the temporary data frame
        temp_df.drop(columns='random', inplace=True)
    
    sorted_terms = np.array(sorted_terms)
    measure_term_pair = zip(bursty_measure_names, sorted_terms)
    sorted_measures = dict(measure_term_pair)
    return sorted_measures
    
def calculate_means(nested_list):
    result = []
    num_outer = len(nested_list)
    num_inner = len(nested_list[0])

    for i in range(num_inner):
        means = {}
        for column in nested_list[0][i].columns:
            values = [nested_list[outer][i][column].values for outer in range(num_outer)]
            mean_values = np.mean(values, axis=0)
            means[column] = mean_values
        result.append(pd.DataFrame(means, index=nested_list[0][i].index))
    return result

# Function to calculate the standard deviation of the corresponding data frames
def calculate_sds(nested_list):
    result = []
    num_outer = len(nested_list)
    num_inner = len(nested_list[0])

    for i in range(num_inner):
        std_devs = {}
        for column in nested_list[0][i].columns:
            values = [nested_list[outer][i][column].values for outer in range(num_outer)]
            std_values = np.std(values, axis=0, ddof=1)
            std_devs[column] = std_values
        result.append(pd.DataFrame(std_devs, index=nested_list[0][i].index))
    return result

def create_pk(v, sorted_measures, k_values):
  measures = sorted_measures.keys()
  counts = [[], [], [], [], [], [], [], [], [], []]
  pk_dct = dict(zip(measures, counts))  
  for measure in pk_dct.keys():
      for k in k_values:
              pk_dct[measure].append(count_words(top_k(sorted_measures, k)[measure], v)/k)
  result = pd.DataFrame(pk_dct)
  result.index = k_values
  return result

def create_rk2(v, sorted_measures, k_values):
  measures = sorted_measures.keys()
  counts = [[], [], [], [], [], [], [], [], [], []]
  rk_dct = dict(zip(measures, counts))  
  for measure in rk_dct.keys():
    for k in k_values:
      rk_dct[measure].append(count_words(top_k(sorted_measures, k)[measure], v)/k)
  result = pd.DataFrame(rk_dct)
  result.index = k_values
  return result

def create_f1k(v, sorted_measures, k_values):
  measures = sorted_measures.keys()
  counts = [[], [], [], [], [], [], [], [], [], []]
  f1k_dct = dict(zip(measures, counts))  
  for measure in f1k_dct.keys():
    for k in k_values:
      f1k_dct[measure].append(count_words(top_k(sorted_measures, k)[measure], v)/k)
  result = pd.DataFrame(f1k_dct)
  result.index = k_values
  return result

def create_RBO(v, sorted_measures, k_values):
  RICF = sorted_measures["RICF"]
  measures = sorted_measures.keys()
  counts = [[], [], [], [], [], [], [], [], [], []]
  rbo_dct = dict(zip(measures, counts))  
  for measure in rbo_dct.keys():
    for k in k_values:
      S = top_k(sorted_measures, k)[measure]
      T = RICF[0:k]
      rbo_dct[measure].append(rbo.RankingSimilarity(S, T).rbo())
  result = pd.DataFrame(rbo_dct)
  result.index = k_values
  return result

def count_words(lst, imp_words):
  counter = 0
  for x in lst:
    if x in imp_words:
      counter += 1
  return counter

In [36]:
# Initialize a random seed to ensure results can be replicated
np.random.seed(641369)

def create_rk(lex_units, sorted_measures, k_values):
  measures = sorted_measures.keys()
  counts = [[], [], [], [], [], [], [], [], [], []]
  rk_dct = dict(zip(measures, counts))  
  for measure in rk_dct.keys():
    for k in k_values:
      rk_dct[measure].append(count_words(top_k(sorted_measures, k)[measure], lex_units)/len(lex_units))
  result = pd.DataFrame(rk_dct)
  result.index = k_values
  return result


# These are the Precision @ k, Recall @ k and Rank Biased Overlap scores
all_pk_scores = []
all_rk_scores = []
all_rbo_scores = []

# Used as inputs for calculating the various scores
k_values = np.array([10, 50, 100, 500, 1000, 5000])
categories = {'all': genia_lexical_units , 'amino_acid': amino_acid, 'nucleotide': nucleotide, 'multi_cell': multi_cell, 'cell': cell, 'other': other}
#relevant_instance_counts = np.array(lex_unit_counts)
#relevant_instance_counts = np.insert(relevant_instance_counts, 0, relevant_instance_counts.sum(), axis=0)

# R = 100
R = 2 # For testing purposes; change back to 100 for final results
for r in tqdm(range(R)):
    pk_scores = []
    rk_scores = []
    sorted_measures = resort(term_scores_df)
    for category, lex_units in categories.items():
        #print('k =', category)
        #print('#v =', len(lex_units))
        pk = create_pk(lex_units, sorted_measures, k_values)
        pk_scores.append(pk)
        rk = create_rk(lex_units, sorted_measures, k_values)
        rk_scores.append(rk)
        rbo_scores = create_RBO(lex_units, sorted_measures, k_values)
    all_pk_scores.append(pk_scores)
    all_rk_scores.append(rk_scores)
    all_rbo_scores.append(rbo_scores)  
print("Done")

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [01:09<00:00, 34.78s/it]

Done

In [37]:
# Calculate mean P@k scores and display to console
all_pk_scores_means = calculate_means(all_pk_scores)
print("Mean P@k scores:")
with pd.option_context('display.precision', 4):
    display(all_pk_scores_means[0])
    display(all_pk_scores_means[1])
    display(all_pk_scores_means[2])
    display(all_pk_scores_means[3])
    display(all_pk_scores_means[4])
    display(all_pk_scores_means[5])

Mean P@k scores:

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.7500  0.8500  0.9000  1.0000  1.0000  0.9000  1.0000
50    0.8400  0.9000  0.9200  0.9600  1.0000  0.7700  1.0000
100   0.8550  0.8850  0.9300  0.9800  0.9800  0.7800  1.0000
500   0.8610  0.8490  0.9420  0.9830  0.9740  0.8260  0.9920
1000  0.8605  0.8490  0.9510  0.9810  0.9640  0.8535  0.9865
5000  0.8584  0.8478  0.9151  0.9277  0.8972  0.8753  0.9315

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.1500  0.3000  0.7000  1.0000  0.8000  0.1500  1.0000
50    0.2300  0.2700  0.5700  0.7500  0.7000  0.2100  0.7900
100   0.2600  0.2900  0.5500  0.8200  0.7450  0.1350  0.8300
500   0.2480  0.2560  0.5540  0.6860  0.6220  0.2200  0.6910
1000  0.2640  0.2470  0.5475  0.6400  0.5895  0.2525  0.6440
5000  0.2696  0.2439  0.4288  0.4276  0.4110  0.2800  0.4289

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.1500  0.1500   0.100  0.0000  0.1000  0.0000  0.0000
50    0.1900  0.1500   0.060  0.1000  0.1200  0.1200  0.1000
100   0.1700  0.1400   0.070  0.1000  0.1000  0.1450  0.1100
500   0.1720  0.1530   0.141  0.1440  0.1460  0.1370  0.1450
1000  0.1555  0.1560   0.149  0.1295  0.1390  0.1400  0.1335
5000  0.1527  0.1577   0.153  0.1547  0.1483  0.1529  0.1558

         IDF    ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.1000  0.100  0.0000  0.0000  0.0000  0.0000  0.0000
50    0.0300  0.050  0.0200  0.0400  0.0400  0.0800  0.0400
100   0.0200  0.035  0.0350  0.0200  0.0200  0.0900  0.0200
500   0.0320  0.042  0.0430  0.0340  0.0320  0.0560  0.0340
1000  0.0350  0.039  0.0440  0.0365  0.0420  0.0530  0.0360
5000  0.0377  0.037  0.0438  0.0444  0.0413  0.0468  0.0444

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.1000  0.1000  0.1000  0.0000  0.0000  0.0500  0.0000
50    0.0900  0.1300  0.1400  0.0100  0.0000  0.1600  0.0100
100   0.0950  0.1300  0.1200  0.0100  0.0200  0.1200  0.0100
500   0.1210  0.1100  0.0830  0.0390  0.0600  0.0900  0.0370
1000  0.1225  0.1130  0.0825  0.0625  0.0695  0.0920  0.0610
5000  0.1117  0.1095  0.0953  0.1001  0.0986  0.0947  0.1007

         IDF     ICF  Chi-sq      CG    ICB     DoP    RICF
10    0.2500  0.2000  0.0000  0.0000  0.100  0.7000  0.0000
50    0.3000  0.3000  0.1300  0.0600  0.140  0.2000  0.0600
100   0.3100  0.2900  0.1550  0.0300  0.095  0.2900  0.0300
500   0.2880  0.2880  0.1210  0.0800  0.114  0.3230  0.0850
1000  0.2835  0.2940  0.1280  0.1125  0.124  0.3160  0.1120
5000  0.2867  0.2997  0.1942  0.2009  0.198  0.3009  0.2017

In [17]:
# Calculate standard deviation of P@k scores and display to console
all_pk_scores_sds = calculate_sds(all_pk_scores)
print("P@k scores standard deviations:")
with pd.option_context('display.precision', 4):
    display(all_pk_scores_sds[0])
    display(all_pk_scores_sds[1])
    display(all_pk_scores_sds[2])
    display(all_pk_scores_sds[3])
    display(all_pk_scores_sds[4])
    display(all_pk_scores_sds[5])

P@k scores standard deviations:

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0707  0.2121  0.0000  0.0000  0.0000  0.0000  0.0000
50    0.0849  0.0283  0.0283  0.0000  0.0000  0.0141  0.0000
100   0.0636  0.0354  0.0141  0.0000  0.0000  0.0000  0.0000
500   0.0212  0.0014  0.0028  0.0014  0.0000  0.0000  0.0000
1000  0.0134  0.0057  0.0042  0.0028  0.0014  0.0007  0.0021
5000  0.0042  0.0008  0.0013  0.0004  0.0003  0.0001  0.0001

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.2121  0.1414  0.1414  0.0000  0.0000  0.0707  0.0000
50    0.0990  0.0424  0.0990  0.0141  0.0000  0.0141  0.0141
100   0.0000  0.0141  0.0566  0.0000  0.0071  0.0071  0.0000
500   0.0141  0.0141  0.0226  0.0000  0.0000  0.0000  0.0071
1000  0.0156  0.0099  0.0120  0.0000  0.0007  0.0007  0.0071
5000  0.0068  0.0078  0.0011  0.0006  0.0003  0.0000  0.0004

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.2121  0.2121  0.1414  0.0000  0.0000  0.0000  0.0000
50    0.0141  0.0141  0.0283  0.0000  0.0000  0.0000  0.0000
100   0.0141  0.0283  0.0424  0.0000  0.0000  0.0071  0.0000
500   0.0085  0.0014  0.0184  0.0000  0.0000  0.0014  0.0014
1000  0.0007  0.0113  0.0085  0.0007  0.0000  0.0014  0.0007
5000  0.0041  0.0092  0.0006  0.0016  0.0001  0.0001  0.0003

         IDF     ICF  Chi-sq      CG     ICB  DoP    RICF
10    0.1414  0.0000  0.0000  0.0000  0.0000  0.0  0.0000
50    0.0141  0.0141  0.0283  0.0000  0.0000  0.0  0.0000
100   0.0000  0.0071  0.0071  0.0000  0.0000  0.0  0.0000
500   0.0141  0.0028  0.0042  0.0000  0.0000  0.0  0.0028
1000  0.0113  0.0085  0.0057  0.0007  0.0000  0.0  0.0014
5000  0.0010  0.0008  0.0003  0.0006  0.0001  0.0  0.0003

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0000  0.1414  0.0000  0.0000  0.0000  0.0707  0.0000
50    0.0141  0.0990  0.0283  0.0141  0.0000  0.0000  0.0141
100   0.0354  0.0566  0.0283  0.0000  0.0000  0.0000  0.0000
500   0.0297  0.0085  0.0099  0.0014  0.0000  0.0000  0.0014
1000  0.0106  0.0042  0.0092  0.0021  0.0007  0.0000  0.0014
5000  0.0035  0.0024  0.0001  0.0004  0.0000  0.0001  0.0004

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.2121  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000
50    0.0566  0.0283  0.0424  0.0000  0.0000  0.0000  0.0000
100   0.0424  0.0283  0.0071  0.0000  0.0071  0.0000  0.0000
500   0.0113  0.0000  0.0127  0.0000  0.0000  0.0014  0.0014
1000  0.0021  0.0085  0.0141  0.0007  0.0000  0.0000  0.0028
5000  0.0021  0.0038  0.0011  0.0007  0.0003  0.0001  0.0001

In [38]:
# Calculate mean R@k scores and display to console
all_rk_scores_means = calculate_means(all_rk_scores)
print("Mean R@k scores:")
with pd.option_context('display.precision', 4):
    display(all_rk_scores_means[0])
    display(all_rk_scores_means[1])
    display(all_rk_scores_means[2])
    display(all_rk_scores_means[3])
    display(all_rk_scores_means[4])
    display(all_rk_scores_means[5])

Mean R@k scores:

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0002  0.0003  0.0003  0.0003  0.0003  0.0003  0.0003
50    0.0013  0.0014  0.0014  0.0015  0.0016  0.0012  0.0016
100   0.0027  0.0028  0.0029  0.0031  0.0031  0.0025  0.0031
500   0.0135  0.0134  0.0148  0.0155  0.0153  0.0130  0.0156
1000  0.0271  0.0267  0.0299  0.0309  0.0303  0.0269  0.0310
5000  0.1350  0.1334  0.1439  0.1459  0.1411  0.1377  0.1465

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0001  0.0003  0.0007  0.0010  0.0008  0.0001  0.0010
50    0.0011  0.0013  0.0028  0.0037  0.0034  0.0010  0.0039
100   0.0026  0.0029  0.0054  0.0081  0.0073  0.0013  0.0082
500   0.0122  0.0126  0.0273  0.0338  0.0306  0.0108  0.0340
1000  0.0260  0.0243  0.0539  0.0630  0.0581  0.0249  0.0634
5000  0.1327  0.1201  0.2111  0.2105  0.2024  0.1379  0.2112

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0003  0.0003  0.0002  0.0000  0.0002  0.0000  0.0000
50    0.0017  0.0013  0.0005  0.0009  0.0011  0.0011  0.0009
100   0.0030  0.0025  0.0013  0.0018  0.0018  0.0026  0.0020
500   0.0154  0.0137  0.0126  0.0129  0.0131  0.0123  0.0130
1000  0.0279  0.0280  0.0267  0.0232  0.0249  0.0251  0.0240
5000  0.1370  0.1415  0.1372  0.1388  0.1330  0.1372  0.1398

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0007  0.0007  0.0000  0.0000  0.0000  0.0000  0.0000
50    0.0010  0.0017  0.0007  0.0014  0.0014  0.0028  0.0014
100   0.0014  0.0024  0.0024  0.0014  0.0014  0.0062  0.0014
500   0.0111  0.0145  0.0149  0.0118  0.0111  0.0194  0.0118
1000  0.0242  0.0270  0.0305  0.0253  0.0291  0.0367  0.0249
5000  0.1305  0.1281  0.1517  0.1537  0.1430  0.1620  0.1537

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0002  0.0002  0.0002  0.0000  0.0000  0.0001  0.0000
50    0.0011  0.0016  0.0017  0.0001  0.0000  0.0020  0.0001
100   0.0023  0.0032  0.0030  0.0002  0.0005  0.0030  0.0002
500   0.0149  0.0136  0.0102  0.0048  0.0074  0.0111  0.0046
1000  0.0302  0.0279  0.0204  0.0154  0.0172  0.0227  0.0151
5000  0.1379  0.1352  0.1176  0.1235  0.1217  0.1169  0.1243

         IDF     ICF  Chi-sq      CG         ICB     DoP    RICF
10    0.0002  0.0002  0.0000  0.0000  9.4697e-05  0.0007  0.0000
50    0.0014  0.0014  0.0006  0.0003  6.6288e-04  0.0009  0.0003
100   0.0029  0.0027  0.0015  0.0003  8.9962e-04  0.0027  0.0003
500   0.0136  0.0136  0.0057  0.0038  5.3977e-03  0.0153  0.0040
1000  0.0268  0.0278  0.0121  0.0107  1.1742e-02  0.0299  0.0106
5000  0.1357  0.1419  0.0920  0.0951  9.3750e-02  0.1425  0.0955

In [39]:
# Calculate standard deviation of R@k scores and display to console
all_rk_scores_sds = calculate_sds(all_rk_scores)
print("R@k scores standard deviations:")
with pd.option_context('display.precision', 4):
    display(all_rk_scores_sds[0])
    display(all_rk_scores_sds[1])
    display(all_rk_scores_sds[2])
    display(all_rk_scores_sds[3])
    display(all_rk_scores_sds[4])
    display(all_rk_scores_sds[5])

R@k scores standard deviations:

,IDF,ICF,Chi-sq,CG,ICB,DoP,RICF
10,2.2245e-05,6.6735e-05,0.0000e+00,0.0000e+00,0.0000e+00,0.0000e+00,0.0000e+00
50,1.3347e-04,4.4490e-05,4.4490e-05,0.0000e+00,0.0000e+00,2.2245e-05,0.0000e+00
100,2.0021e-04,1.1123e-04,4.4490e-05,0.0000e+00,0.0000e+00,0.0000e+00,0.0000e+00
500,3.3368e-04,2.2245e-05,4.4490e-05,2.2245e-05,0.0000e+00,0.0000e+00,0.0000e+00
1000,4.2266e-04,1.7796e-04,1.3347e-04,8.8981e-05,4.4490e-05,2.2245e-05,6.6735e-05
5000,6.6735e-04,1.3347e-04,2.0021e-04,6.6735e-05,4.4490e-05,2.2245e-05,2.2245e-05

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10    0.0002  0.0001  0.0001  0.0000e+00  0.0000e+00  6.9631e-05  0.0000e+00
50    0.0005  0.0002  0.0005  6.9631e-05  0.0000e+00  6.9631e-05  6.9631e-05
100   0.0000  0.0001  0.0006  0.0000e+00  6.9631e-05  6.9631e-05  0.0000e+00
500   0.0007  0.0007  0.0011  0.0000e+00  0.0000e+00  0.0000e+00  3.4816e-04
1000  0.0015  0.0010  0.0012  0.0000e+00  6.9631e-05  6.9631e-05  6.9631e-04
5000  0.0033  0.0038  0.0006  2.7853e-04  1.3926e-04  0.0000e+00  2.0889e-04

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0004  0.0004  0.0003  0.0000  0.0000  0.0000  0.0000
50    0.0001  0.0001  0.0003  0.0000  0.0000  0.0000  0.0000
100   0.0003  0.0005  0.0008  0.0000  0.0000  0.0001  0.0000
500   0.0008  0.0001  0.0016  0.0000  0.0000  0.0001  0.0001
1000  0.0001  0.0020  0.0015  0.0001  0.0000  0.0003  0.0001
5000  0.0037  0.0082  0.0005  0.0014  0.0001  0.0001  0.0003

         IDF     ICF  Chi-sq      CG     ICB  DoP   RICF
10    0.0010  0.0000  0.0000  0.0000  0.0000  0.0  0.000
50    0.0005  0.0005  0.0010  0.0000  0.0000  0.0  0.000
100   0.0000  0.0005  0.0005  0.0000  0.0000  0.0  0.000
500   0.0049  0.0010  0.0015  0.0000  0.0000  0.0  0.001
1000  0.0078  0.0059  0.0039  0.0005  0.0000  0.0  0.001
5000  0.0034  0.0029  0.0010  0.0020  0.0005  0.0  0.001

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0000  0.0003  0.0000  0.0000  0.0000  0.0002  0.0000
50    0.0002  0.0012  0.0003  0.0002  0.0000  0.0000  0.0002
100   0.0009  0.0014  0.0007  0.0000  0.0000  0.0000  0.0000
500   0.0037  0.0010  0.0012  0.0002  0.0000  0.0000  0.0002
1000  0.0026  0.0010  0.0023  0.0005  0.0002  0.0000  0.0003
5000  0.0044  0.0030  0.0002  0.0005  0.0000  0.0002  0.0005

,IDF,ICF,Chi-sq,CG,ICB,DoP,RICF
10,0.0002,0.0000,0.0000e+00,0.0000e+00,0.0000e+00,0.0000e+00,0.0000e+00
50,0.0003,0.0001,2.0088e-04,0.0000e+00,0.0000e+00,0.0000e+00,0.0000e+00
100,0.0004,0.0003,6.6961e-05,0.0000e+00,6.6961e-05,0.0000e+00,0.0000e+00
500,0.0005,0.0000,6.0265e-04,0.0000e+00,0.0000e+00,6.6961e-05,6.6961e-05
1000,0.0002,0.0008,1.3392e-03,6.6961e-05,0.0000e+00,0.0000e+00,2.6784e-04
5000,0.0010,0.0018,5.3569e-04,3.3480e-04,1.3392e-04,6.6961e-05,6.6961e-05

In [89]:
def calculate_mean_rbo_scores(scores_list):
    R = len(scores_list) # Number of replicates
    H = len(scores_list[0]) # Number of dispersion metrics
    d_metrics = scores_list[0].columns # Dispersion metrics by name
    k_values = scores_list[0].index # Top k values
    result = {}
    
    for d_metric in d_metrics:
        scores = [scores_list[r][d_metric].values for r in range(R)]
        mean_scores = np.mean(scores, axis=0)
        result[d_metric] = mean_scores
        
    return pd.DataFrame(result, index=k_values)

# Calculate mean RBO scores and display to console
mean_rbo_scores = calculate_mean_rbo_scores(all_rbo_scores)
  
with pd.option_context('display.precision', 4):
    display(mean_rbo_scores)

         IDF  ICF  Chi-sq      CG     ICB     DoP  RICF
10    0.0000  0.0  0.0000  0.9090  0.5969  0.0000   1.0
50    0.0000  0.0  0.0041  0.8952  0.6917  0.0000   1.0
100   0.0000  0.0  0.0125  0.9041  0.7016  0.0000   1.0
500   0.0088  0.0  0.1019  0.9303  0.7271  0.0005   1.0
1000  0.0140  0.0  0.2026  0.9350  0.7653  0.0029   1.0
5000  0.0592  0.0  0.6548  0.9068  0.7963  0.0426   1.0

In [22]:
# Calculate mean P@k scores and write to CSV
pd.DataFrame(calculate_means(all_pk_scores)[0]).to_csv('table-4/table-4-all-means.csv', index=False)
pd.DataFrame(calculate_means(all_pk_scores)[1]).to_csv('table-4/table-4-amino_acid-means.csv', index=False)
pd.DataFrame(calculate_means(all_pk_scores)[2]).to_csv('table-4/table-4-nucleotide-means.csv', index=False)
pd.DataFrame(calculate_means(all_pk_scores)[3]).to_csv('table-4/table-4-multicell-means.csv', index=False)
pd.DataFrame(calculate_means(all_pk_scores)[4]).to_csv('table-4/table-4-cell-means.csv', index=False)
pd.DataFrame(calculate_means(all_pk_scores)[5]).to_csv('table-4/table-4-other-means.csv', index=False)

# Calculate standard deviations for P@k scores and write to CSV
pd.DataFrame(calculate_sds(all_pk_scores)[0]).to_csv('table-4/table-4-all-sds.csv', index=False)
pd.DataFrame(calculate_sds(all_pk_scores)[1]).to_csv('table-4/table-4-amino_acid-sds.csv', index=False)
pd.DataFrame(calculate_sds(all_pk_scores)[2]).to_csv('table-4/table-4-nucleotide-sds.csv', index=False)
pd.DataFrame(calculate_sds(all_pk_scores)[3]).to_csv('table-4/table-4-multicell-sds.csv', index=False)
pd.DataFrame(calculate_sds(all_pk_scores)[4]).to_csv('table-4/table-4-cell-sds.csv', index=False)
pd.DataFrame(calculate_sds(all_pk_scores)[5]).to_csv('table-4/table-4-other-sds.csv', index=False)

## Top 10 Ranked Terms Example

Here we reproduce the result of Table 5 from the manuscript.

In [23]:
# Initialize a random seed to ensure results can be replicated
np.random.seed(641369)

In [ ]:
ranked_terms_df = resort(term_scores_df)
top_10_ranked_terms_df = pd.DataFrame(top_k(ranked_terms_df, 10))
display(top_10_ranked_terms_df)

In [25]:
# Write to CSV
top_10_ranked_terms_df.to_csv('table-5/table-5.csv', index=False)

## Stopwords Exploratory Analysis

Here we reproduce the result of Table 6 from the manuscript.

In [ ]:
import pandas as pd
from nltk.corpus import stopwords

# Ensure you have the stopwords downloaded
import nltk
nltk.download('stopwords')

def getrank(sorted_measures):
    unique_terms = set()
    for terms in sorted_measures.values():
        unique_terms.update(terms)
    unique_terms = sorted(unique_terms)
    
    # Create a data frame to hold the rankings
    ranking_df = pd.DataFrame(index=unique_terms, columns=sorted_measures.keys())
    
    # Fill the data frame with rankings
    for measure, terms in sorted_measures.items():
        for rank, term in enumerate(terms):
            ranking_df.at[term, measure] = rank + 1  # Rank starts from 1
    
    # Replace NaN with a large number to indicate unranked terms
    ranking_df = ranking_df.fillna(len(unique_terms) + 1)
    #csv_file_path = 'ranking_table.csv'
    #ranking_df.to_csv(csv_file_path)
    return ranking_df

# Function to filter stopwords from the ranking data frame
def filter_stopwords(ranking_df):
    stopwords_list = set(stopwords.words('english'))
    
    # Filter the data frame to include only stopwords
    stopwords_rank = ranking_df[ranking_df.index.isin(stopwords_list)]
    
    # Save the stopwords ranking data frame to a CSV file
    #csv_file_path = 'stopwords_ranking_table.csv'
    #stopwords_rank.to_csv(csv_file_path)
    
    return stopwords_rank

In [ ]:
# Initialize a random seed to ensure results can be replicated
np.random.seed(641369)

# Generate term dispersion ranks for R different versions of the data
R = 100
all_quantiles_df = []
for r in tqdm(range(R)):
    sorted_measures = resort(term_scores_df)
    rank = getrank(sorted_measures)
    stopwords_ranks_df = filter_stopwords(rank)
    bursty_measure_names = stopwords_ranks_df.head(0)
    quantiles = []
    for bursty_measure_name in bursty_measure_names:
        quantiles.append(stopwords_ranks_df[bursty_measure_name].quantile([0, 0.25, 0.5, 0.75, 1]))
    quantiles_df = pd.DataFrame(quantiles)
    all_quantiles_df.append(quantiles_df)

In [28]:
# Extract the column and index names from the first quantiles data frame
columns = all_quantiles_df[0].columns
index = all_quantiles_df[0].index

# Initialize empty data frames to store the mean and standard deviation values
mean_df = pd.DataFrame(index=index, columns=columns)
std_df = pd.DataFrame(index=index, columns=columns)

# Compute the mean and standard deviation of corresponding elements across all matrices
for col in columns:
    for idx in index:
        values = [matrix.at[idx, col] for matrix in all_quantiles_df]
        mean_df.at[idx, col] = np.mean(values)
        std_df.at[idx, col] = np.std(values)

In [ ]:
# Display the resulting data frames
print("Mean values:")
with pd.option_context('display.precision', 4):
    display(mean_df)
print("\nStandard deviations:")
with pd.option_context('display.precision', 4):
    display(std_df)

In [30]:
# Write to CSV
mean_df.to_csv('table-6/table-6-means.csv')
std_df.to_csv('table-6/table-6-sds.csv')