# Evaluate Term Dispersion Scores on the GENIA Corpus Data and Reproduce Results Reported in the Mannuscript 

Authors: Samuel Sarria Hurtado, Uyen "Rachel" Lai, and Paul Sheridan

Last update: 2025-06-03

Description: Evaluate the following term dispersion scores on the Genia corpus data:
- Inverse Document Frequency (IDF)
- Inverse Collection Frequency (ICF)
- Chi-square
- Church and Gale (CG)
- Irvine and Callison-Burch (ICB)
- Derivation of Proportions (DoP)
- Residual ICF (RICF)

Calculate average P@k scores for each scoring function using the GENIA terms as ground truth. Also, evaluate scoring functions for their ability to filter out stopwords.

## Preliminaries

In [1]:
# Imports
import sys
import json
import pandas as pd
sys.path.append('../0-base-functions/')
import wordstats
from sklearn.feature_extraction.text import CountVectorizer
import random
import numpy as np
import scipy
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from io import StringIO
from numpy import nan
from tqdm import tqdm
import rbo
import pickle

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/pasheridan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

## Load the GENIA Corpus Data

In particular, we load the
- preprocessed GENIA corpus documents,
- and gold standard biological terms (i.e., lexical units) and their associated semantic classes (i.e., sems).

In [2]:
# Load the preprocessed GENIA corpus documents
genia_corpus_path = '../1-preprocessing/GENIAcorpus3.02-preprocessed.json'

with open(genia_corpus_path, "r") as j:
  genia_corpus = json.loads(j.read())

# Load gold standard terms 
genia_keywords_path = '../1-preprocessing/GENIAcorpus3.02-keywords.tsv'

with open(genia_keywords_path, "r") as c:
  genia_lexical_units_and_sems = pd.read_csv(c, sep='\t')

genia_lexical_units = genia_lexical_units_and_sems.lex.to_numpy()

## Prepare the GENIA Corpus Data for Analysis

Prepare the corpus vocabulary.

In [3]:
# Compile the GENIA corpus vocabulary
pre_vocab = []
for i in range(len(genia_corpus)):
  pre_vocab.append(genia_corpus[i].split())

vocab = []
for i in range(len(pre_vocab)):
  for j in range(len(pre_vocab[i])):
    vocab.append(pre_vocab[i][j])

vocab = list(set(vocab))
vocab.sort()

Convert GENIA documents into term-in-document matrix of token counts.

In [4]:
# Helper function to ensure that CountVectorizer doesn't ignore any terms
def analyzer_custom(doc):
  return doc.split()

# Generate term-in-document counts
counter = CountVectorizer(lowercase=False, vocabulary=vocab, analyzer=analyzer_custom)
collection = counter.transform(genia_corpus)

## Evaluate Term Dispersion Scores for Selected Measures

Calculate bag-of-words model word statistics and related quantities.

In [5]:
# Calculate word statistics and related quantities
m = len(counter.get_feature_names_out()) # vocab size
d = collection.shape[0] # collection size
N_i = wordstats.get_Ni(collection)
N_j = wordstats.get_Nj(collection)
N = wordstats.get_N(N_j)
B_ij = wordstats.get_Bij(collection)
B_i = wordstats.get_Bi(B_ij)
B_j = wordstats.get_Bj(B_ij)
DF = wordstats.get_DF(B_i, d)
CF = wordstats.get_CF(N_i)
nij_by_nj = wordstats.get_nij_by_nj(collection, N_j)
thetas = np.array(range(1, max(N_i.A[0]) + 1))/N
opt_thetas = wordstats.get_opt_thetas(N, m, d, N_i, N_j, B_i, thetas)

Evaluate word dispersion scores.

In [6]:
# Calculate word dispersion scores according the various measures used in this study
IDF = wordstats.get_IDF(DF)
ICF = wordstats.get_ICF(CF)
Chisq = wordstats.get_Chisq(collection)
CG = wordstats.get_CG(N_i, B_i)
ICB = wordstats.get_ICB(nij_by_nj, B_i)
DoP = wordstats.get_DoP(collection, N_i, N_j, N)
RICF = wordstats.get_RICF(opt_thetas, N, ICF)

/Users/pasheridan/Desktop/github-repos/bursty-term-measure/genia/3-tables/../0-base-functions/wordstats.py:209: RuntimeWarning: divide by zero encountered in log
  return -np.log(chisq_values)

Arrange term dispersion scores into a data frame.

In [7]:
# Initialize dispersion scores data frame
term_scores_df = pd.DataFrame(data=
                         {'term': counter.get_feature_names_out(),
                          'IDF': IDF.A[0],
                          'ICF': ICF.A[0],
                          'Chi-sq': Chisq,
                          'CG': CG.A[0],
                          'ICB': ICB.A[0],
                          'DoP': DoP.A[0],
                          'RICF': RICF.A[0]})

# Print term dispersion scores to console
display(term_scores_df)

# Write to TSV
term_scores_df.to_csv('term-dispersion-scores.tsv', sep='\t')

,term,IDF,ICF,Chi-sq,CG,ICB,DoP,RICF
0,'aged'_lymphocyte_lex,7.600902,12.800954,0.701595,1.0,244.0,-0.000673,-0.000251
1,'converted'_TCEd_motif_lex,7.600902,12.800954,0.701595,1.0,195.0,-0.000538,-0.000251
2,'latency_I'_lex,7.600902,12.800954,0.701595,1.0,206.0,-0.000568,-0.000251
3,'latency_II'_lex,7.600902,12.800954,0.701595,1.0,206.0,-0.000568,-0.000251
4,'master_regulator_lex,7.600902,12.800954,0.701595,1.0,63.0,-0.000174,-0.000251
...,...,...,...,...,...,...,...,...
40799,zymogen_plasma_factor_X_lex,7.600902,12.800954,0.701595,1.0,355.0,-0.000979,-0.000251
40800,zymogen_plasma_factors_VII_lex,7.600902,12.800954,0.701595,1.0,355.0,-0.000979,-0.000251
40801,zymography_lex,7.600902,12.800954,0.701595,1.0,191.0,-0.000527,-0.000251
40802,zymosan-treated_cell_lex,7.600902,12.800954,0.701595,1.0,225.0,-0.000621,-0.000251
40803,zymosan_lex,6.907755,11.414659,587.746183,2.0,458.0,-0.001285,0.692615

## Compile GENIA Corpus Summary Statistics

This is the result of Table 3 from the manuscript.

In [8]:
# Collect lexical units belonging to a given high-level semantic class
def get_high_level_semantic_class_words(high_level_class_lst):
  words = []
  for k, v in lex_sem_dct.items():
    if v in high_level_class_lst:
      words.append(k)
  return words

# Hardcode the semantic classes according to their high-level designations.
amino_acid_sems = ['G#amino_acid_monomer', 'G#peptide', 'G#protein_N/A',
              'G#protein_complex', 'G#protein_domain_or_region',
              'G#protein_family_or_group', 'G#protein_molecule',
              'G#protein_substructure', 'G#protein_subunit',
              'G#other_organic_compound', 'G#organic', 'G#inorganic', 'G#atom',
              'G#carbohydrate', 'G#lipid']
nucleotide_sems = ['G#nucleotide', 'G#polynucleotide', 'G#DNA_N/A',
        'G#DNA_domain_or_region', 'G#DNA_family_or_group', 'G#DNA_molecule',
        'G#DNA_substructure', 'G#RNA_N/A', 'G#RNA_domain_or_region',
        'G#RNA_family_or_group', 'G#RNA_molecule', 'G#RNA_substructure']
multi_cell_sems = ['G#virus', 'G#mono_cell', 'G#multi_cell', 'G#body_part', 'G#tissue']
cell_sems = ['G#cell_type', 'G#cell_component', 'G#cell_line', 'G#other_artificial_source']
other_sems = ['G#other_name']
high_level_semantic_class_names = ['amino_acid', 'nucleotide', 'multi_cell', 'cell', 'other']
high_level_semantic_class_lex_units = [genia_lexical_units, amino_acid_sems, nucleotide_sems, multi_cell_sems, cell_sems, other_sems]

# Create dictionary of lexical units and their associated semantic classes
sem = np.array(genia_lexical_units_and_sems['sem'])
lex = np.array(genia_lexical_units_and_sems['lex'])
lex_sem_dct = dict(zip(lex, sem))

# Count number of semantic classes in each high-level class
sub_class = [len(amino_acid_sems), len(nucleotide_sems), len(multi_cell_sems), len(cell_sems), len(other_sems)]

# Count number of distinct lexical units in each high-level semantic class
amino_acid = get_high_level_semantic_class_words(amino_acid_sems)
nucleotide = get_high_level_semantic_class_words(nucleotide_sems)
multi_cell = get_high_level_semantic_class_words(multi_cell_sems)
cell = get_high_level_semantic_class_words(cell_sems)
other = get_high_level_semantic_class_words(other_sems)

# Count number of lexical units used as annotations for each high-level semantic class
high_level_class_words = [genia_lexical_units, amino_acid, nucleotide, multi_cell, cell, other]
high_level_class_words_counter = [0, 0, 0, 0, 0, 0]
for i in range(len(high_level_class_words)):
  for j in range(len(vocab)):
    if vocab[j] in high_level_class_words[i]:
      high_level_class_words_counter[i] += N_i.A[0][j]

# Create dictionary of lexical units and their associated semantic classes
sem = np.array(genia_lexical_units_and_sems['sem'])
lex = np.array(genia_lexical_units_and_sems['lex'])
lex_sem_dct = dict(zip(lex, sem))

# Count number of semantic subclasses in each high-level class
subclass_counts = [len(amino_acid_sems), len(nucleotide_sems), len(multi_cell_sems), len(cell_sems), len(other_sems)]

# Gather distinct lexical units for each high-level semantic class
amino_acid = get_high_level_semantic_class_words(amino_acid_sems)
nucleotide = get_high_level_semantic_class_words(nucleotide_sems)
multi_cell = get_high_level_semantic_class_words(multi_cell_sems)
cell = get_high_level_semantic_class_words(cell_sems)
other = get_high_level_semantic_class_words(other_sems)

# Count number of lexical units used as annotations for each high-level semantic class
lex_by_semamtic_class_counts = [0, 0, 0, 0, 0, 0]
for i in range(len(high_level_semantic_class_names)):
  for j in range(len(vocab)):
    if vocab[j] in high_level_semantic_class_names[i]:
      lex_by_semamtic_class_counts[i] += N_i.A[0][j]

# Define the data
high_level_semantic_classes = ['all', 'amino_acid', 'nucleotide', 'multi_cell', 'cell', 'other']
annotations_count_zip = zip(high_level_semantic_classes, high_level_class_words_counter)
annotations_dict = dict(annotations_count_zip)
lex_unit_counts = [len(amino_acid), len(nucleotide), len(multi_cell), len(cell), len(other)]
subclass_counts = [len(amino_acid_sems), len(nucleotide_sems), len(multi_cell_sems), len(cell_sems), len(other_sems)]
annotations = [
    annotations_dict['amino_acid'],
    annotations_dict['nucleotide'],
    annotations_dict['multi_cell'],
    annotations_dict['cell'],
    annotations_dict['other']]

# Create a data frame
genia_summary_stats_df = pd.DataFrame({
    'Semantic class': ['amino_acid', 'nucleotide', 'multi_cell', 'cell', 'other'],
    'Sub-class': subclass_counts,
    'Unique terms': lex_unit_counts,
    "Annotations": annotations
})

In [9]:
# Print GENIA summary statistics
display(genia_summary_stats_df)

# Write to CSV
genia_summary_stats_df.to_csv('table-3/table-3.csv', index=False)

  Semantic class  Sub-class  Unique terms  Annotations
0     amino_acid         15         10155        42478
1     nucleotide         12          5574        11619
2     multi_cell          5          1444         5247
3           cell          4          4051        11626
4          other          1         10560        19999

## Terminology Extraction Task Experiment

Here we reproduce the result of Table 4 from the manuscript.

In [44]:
# Grab the top k terms
def top_k(dct, k):
  keys = dct.keys()
  values = []
  for key in keys:
    values.append(dct[key][:k])
  keys_values_pair = zip(keys, values)
  return dict(keys_values_pair)

# Count up terms
def count_words(lst, imp_words):
  counter = 0
  for x in lst:
    if x in imp_words:
      counter += 1
  return counter

# Randomly resort term dispersion scores data frame
def resort(term_scores_df):
  sorted_terms = []
  bursty_measure_names = term_scores_df.columns.values.tolist()[1:]

  for measure in bursty_measure_names:
      # Copy the data frame and add a random column
      temp_df = term_scores_df.copy()
      temp_df['random'] = np.random.rand(len(temp_df))
        
      # Sort by the measure and the random column
      sorted_df = temp_df[['term', measure, 'random']].sort_values(by=[measure, 'random'], ascending=[False, True])
        
      # Append the sorted terms to the list
      sorted_terms.append(np.array(sorted_df['term']))
        
      # Drop the random column from the temporary data frame
      temp_df.drop(columns='random', inplace=True)
    
  sorted_terms = np.array(sorted_terms)
  measure_term_pair = zip(bursty_measure_names, sorted_terms)
  sorted_measures = dict(measure_term_pair)
    
  return sorted_measures
    
# Calculate Precision at k scores
def calc_pk(lex_units, sorted_measures, k_values):
  measures = sorted_measures.keys()
  counts = [[], [], [], [], [], [], [], [], [], []]
  pk_dct = dict(zip(measures, counts))  
  for measure in pk_dct.keys():
      for k in k_values:
          pk_dct[measure].append(count_words(top_k(sorted_measures, k)[measure], lex_units)/k)
  result = pd.DataFrame(pk_dct)
  result.index = k_values
  return result

# Calculate Recall at k scores
def calc_rk(lex_units, sorted_measures, k_values):
  measures = sorted_measures.keys()
  counts = [[], [], [], [], [], [], [], [], [], []]
  rk_dct = dict(zip(measures, counts))  
  for measure in rk_dct.keys():
      for k in k_values:
          rk_dct[measure].append(count_words(top_k(sorted_measures, k)[measure], lex_units)/len(lex_units))
  result = pd.DataFrame(rk_dct)
  result.index = k_values
  return result

# Calculate F1 at k scores
def calc_fk(pk, rk):
  result = 2 * (pk * rk) / (pk + rk)
  result = result.fillna(0) # Nan scores are redefined as 0
  return result

# Calculate Rank Biased Overlap scores
def calc_rbo(sorted_measures, k_values):
  RICF = sorted_measures["RICF"]
  measures = sorted_measures.keys()
  counts = [[], [], [], [], [], [], [], [], [], []]
  rbo_dct = dict(zip(measures, counts))  
  for measure in rbo_dct.keys():
      for k in k_values:
          S = top_k(sorted_measures, k)[measure]
          T = RICF[0:k]
          rbo_dct[measure].append(rbo.RankingSimilarity(S, T).rbo())
  result = pd.DataFrame(rbo_dct, index=k_values)
  return result

# Calculate mean P@k, R@k, and F1@k scores
def calc_score_means(nested_list):
    result = []
    num_outer = len(nested_list)
    num_inner = len(nested_list[0])

    for i in range(num_inner):
        means = {}
        for column in nested_list[0][i].columns:
            values = [nested_list[outer][i][column].values for outer in range(num_outer)]
            mean_values = np.mean(values, axis=0)
            means[column] = mean_values
        result.append(pd.DataFrame(means, index=nested_list[0][i].index))
    return result

# Calculate standard deviations of P@k, R@k, and F1@k scores
def calc_score_sds(nested_list):
    result = []
    num_outer = len(nested_list)
    num_inner = len(nested_list[0])

    for i in range(num_inner):
        std_devs = {}
        for column in nested_list[0][i].columns:
            values = [nested_list[outer][i][column].values for outer in range(num_outer)]
            std_values = np.std(values, axis=0, ddof=1)
            std_devs[column] = std_values
        result.append(pd.DataFrame(std_devs, index=nested_list[0][i].index))
    return result

# Calculate mean RBO scores
def calc_mean_rbo_scores(scores_list):
  R = len(scores_list) # Number of replicates
  H = len(scores_list[0]) # Number of dispersion metrics
  d_metrics = scores_list[0].columns # Dispersion metrics by name
  k_values = scores_list[0].index # Top k values
  result = {}
    
  for d_metric in d_metrics:
    scores = [scores_list[r][d_metric].values for r in range(R)]
    mean_scores = np.mean(scores, axis=0)
    result[d_metric] = mean_scores
        
  return pd.DataFrame(result, index=k_values)

In [47]:
# Initialize a random seed to ensure results can be replicated
np.random.seed(641369)

# These are the Precision @ k, Recall @ k and Rank Biased Overlap scores
all_pk_scores = []
all_rk_scores = []
all_fk_scores = []
all_rbo_scores = []

# Used as inputs for calculating the various scores
k_values = np.array([10, 50, 100, 500, 1000, 5000])
categories = {
    'all': genia_lexical_units,
    'amino_acid': amino_acid,
    'nucleotide': nucleotide,
    'multi_cell': multi_cell,
    'cell': cell,
    'other': other}

R = 100
#R = 3 # For testing purposes; change back to 100 for final results
for r in tqdm(range(R)):
    print('r =', r)
    pk_scores = []
    rk_scores = []
    fk_scores = []
    sorted_measures = resort(term_scores_df)
    
    for category, lex_units in categories.items():
        pk = calc_pk(lex_units, sorted_measures, k_values)
        pk_scores.append(pk)
        rk = calc_rk(lex_units, sorted_measures, k_values)
        rk_scores.append(rk)
        fk = calc_fk(pk, rk)
        fk_scores.append(fk)
        rbo_scores = calc_rbo(sorted_measures, k_values)
    all_pk_scores.append(pk_scores)
    all_rk_scores.append(rk_scores)
    all_fk_scores.append(fk_scores)
    all_rbo_scores.append(rbo_scores)

  0%|                                                                                                                        | 0/3 [00:00<?, ?it/s]

r = 0
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000440  0.000629  0.000566  0.000629  0.000629  0.000566  0.000629
50    0.002827  0.002764  0.002953  0.003015  0.003141  0.002450  0.003141
100   0.005645  0.005394  0.005896  0.006147  0.006147  0.004892  0.006272
500   0.027132  0.026326  0.029114  0.030477  0.030167  0.025583  0.030724
1000  0.053070  0.051545  0.058194  0.059719  0.058865  0.052033  0.060085
5000  0.234159  0.230625  0.249001  0.252100  0.243836  0.237964  0.253242
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000590  0.000787  0.001181  0.001968  0.001574  0.000197  0.001968
50    0.002940  0.002940  0.004900  0.007251  0.006859  0.002156  0.007643
100   0.005071  0.005851  0.009946  0.015992  0.014432  0.002730  0.016187
500   0.022337  0.024965  0.053496  0.064383  0.058376  0.020648  0.064383
1000  0.049305  0.045540  0.099686  0.114747  0.105782  0.045361  0.114567
5000  0.181062  0.164566  0.283471  0.282415  0.271066  0.184758  0.283207
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000000  0.001074  0.000716  0.000000  0.000358  0.000000  0.000000
50    0.003556  0.002489  0.001422  0.001778  0.002134  0.002134  0.001778
100   0.005640  0.004230  0.003525  0.003525  0.003525  0.004935  0.003877
500   0.029305  0.025025  0.021073  0.023708  0.024037  0.022391  0.024037
1000  0.047460  0.045026  0.043505  0.039246  0.042288  0.042288  0.040462
5000  0.147153  0.142992  0.144316  0.145262  0.140155  0.144505  0.147153
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.002751  0.001376  0.000000  0.000000  0.000000  0.000000  0.000000
50    0.002677  0.004016  0.002677  0.002677  0.002677  0.005355  0.002677
100   0.002591  0.005181  0.005181  0.002591  0.002591  0.011658  0.002591
500   0.011317  0.020576  0.020576  0.017490  0.016461  0.028807  0.018519
1000  0.022095  0.027005  0.039280  0.030278  0.034370  0.043372  0.030278
5000  0.057418  0.058349  0.067660  0.068281  0.063935  0.072626  0.068591
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000492  0.000000  0.000492  0.000000  0.000000  0.000492  0.000000
50    0.002438  0.001463  0.003901  0.000488  0.000000  0.003901  0.000488
100   0.005782  0.004336  0.006745  0.000482  0.000964  0.005782  0.000482
500   0.031202  0.022852  0.019776  0.008789  0.013184  0.019776  0.008350
1000  0.051475  0.043556  0.035241  0.024154  0.027717  0.036428  0.024550
5000  0.120650  0.119103  0.105182  0.110927  0.108938  0.104740  0.111590

 33%|█████████████████████████████████████▎                                                                          | 1/3 [00:35<01:10, 35.45s/it]

           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000189  0.000378  0.000000  0.000000  0.000189  0.001325  0.000000
50    0.002451  0.003016  0.001508  0.000566  0.001320  0.001885  0.000566
100   0.006379  0.005816  0.002814  0.000563  0.001876  0.005441  0.000563
500   0.026763  0.026040  0.010127  0.007233  0.010307  0.029295  0.007776
1000  0.048789  0.051903  0.020415  0.019377  0.021453  0.054671  0.019723
5000  0.183290  0.194344  0.125321  0.129434  0.127378  0.193445  0.129563
r = 1
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000503  0.000440  0.000566  0.000629  0.000629  0.000566  0.000629
50    0.002450  0.002890  0.002827  0.003015  0.003141  0.002387  0.003141
100   0.005080  0.005708  0.005770  0.006147  0.006147  0.004892  0.006272
500   0.026202  0.026264  0.029238  0.030415  0.030167  0.025583  0.030724
1000  0.051911  0.052033  0.057828  0.059963  0.058743  0.052094  0.060268
5000  0.232528  0.230299  0.248512  0.252263  0.243945  0.237910  0.253187
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000000  0.000394  0.001574  0.001968  0.001574  0.000394  0.001968
50    0.001568  0.002352  0.006271  0.007447  0.006859  0.001960  0.007839
100   0.005071  0.005461  0.011507  0.015992  0.014627  0.002535  0.016187
500   0.024214  0.023088  0.050493  0.064383  0.058376  0.020648  0.065321
1000  0.045361  0.043030  0.096638  0.114747  0.105603  0.045182  0.116360
5000  0.174728  0.157308  0.282415  0.281887  0.271330  0.184758  0.282811
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.001074  0.000000  0.000000  0.000000  0.000358  0.000000  0.000000
50    0.003201  0.002845  0.000711  0.001778  0.002134  0.002134  0.001778
100   0.006345  0.005640  0.001410  0.003525  0.003525  0.005287  0.003877
500   0.027330  0.025354  0.025354  0.023708  0.024037  0.022720  0.023708
1000  0.047155  0.049894  0.047155  0.039550  0.042288  0.042896  0.040767
5000  0.141668  0.155287  0.145073  0.147343  0.140344  0.144695  0.147532
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000000  0.001376  0.000000  0.000000  0.000000  0.000000  0.000000
50    0.001339  0.002677  0.000000  0.002677  0.002677  0.005355  0.002677
100   0.002591  0.003886  0.003886  0.002591  0.002591  0.011658  0.002591
500   0.021605  0.022634  0.023663  0.017490  0.016461  0.028807  0.016461
1000  0.035188  0.036825  0.032733  0.029460  0.034370  0.043372  0.028642
5000  0.059590  0.056487  0.068281  0.069522  0.064246  0.072626  0.069212
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000492  0.000985  0.000492  0.000000  0.000000  0.000000  0.000000
50    0.001951  0.004877  0.002926  0.000000  0.000000  0.003901  0.000000
100   0.003373  0.008191  0.004818  0.000482  0.000964  0.005782  0.000482
500   0.021973  0.025489  0.016700  0.008350  0.013184  0.019776  0.007910
1000  0.045536  0.045931  0.030093  0.025342  0.027321  0.036428  0.023758
5000  0.126174  0.122859  0.105403  0.110264  0.108938  0.104519  0.110927

 67%|██████████████████████████████████████████████████████████████████████████▋                                     | 2/3 [01:10<00:35, 35.32s/it]

           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000757  0.000378  0.000000  0.000000  0.000189  0.001325  0.000000
50    0.003205  0.002639  0.000943  0.000566  0.001320  0.001885  0.000566
100   0.005253  0.005066  0.003002  0.000563  0.001689  0.005441  0.000563
500   0.025316  0.026040  0.011754  0.007233  0.010307  0.029114  0.007595
1000  0.049308  0.049827  0.023875  0.019550  0.021453  0.054671  0.019031
5000  0.185219  0.190874  0.124293  0.128792  0.127121  0.193316  0.129692
r = 2
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000503  0.000440  0.000566  0.000629  0.000629  0.000566  0.000629
50    0.002701  0.002701  0.003015  0.003015  0.003141  0.002387  0.003141
100   0.005519  0.005269  0.006084  0.006147  0.006147  0.004892  0.006272
500   0.026079  0.026017  0.029424  0.030477  0.030167  0.025521  0.030724
1000  0.052582  0.051118  0.057828  0.059963  0.058804  0.052094  0.060024
5000  0.233180  0.230136  0.248457  0.252209  0.243891  0.237964  0.253296
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000394  0.000394  0.001377  0.001968  0.001574  0.000394  0.001968
50    0.003136  0.002744  0.004900  0.007447  0.006859  0.002156  0.007643
100   0.007021  0.005461  0.009556  0.015992  0.014627  0.002730  0.016187
500   0.026654  0.023275  0.046739  0.064758  0.058376  0.020648  0.065134
1000  0.049126  0.043747  0.092873  0.114567  0.105782  0.045361  0.115823
5000  0.176048  0.158364  0.283207  0.283207  0.271066  0.184758  0.283339
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000358  0.000000  0.000000  0.000000  0.000358  0.000000  0.000000
50    0.000711  0.001778  0.002845  0.001778  0.002134  0.002134  0.001778
100   0.002820  0.004230  0.006697  0.003525  0.003525  0.004935  0.003877
500   0.022061  0.024695  0.025683  0.023378  0.024037  0.022391  0.023708
1000  0.041071  0.045330  0.047155  0.041679  0.042592  0.042592  0.041071
5000  0.144884  0.142614  0.144127  0.146019  0.140155  0.144316  0.147153
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.001376  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
50    0.004016  0.001339  0.001339  0.002677  0.002677  0.005355  0.002677
100   0.006477  0.002591  0.005181  0.002591  0.002591  0.011658  0.002591
500   0.015432  0.017490  0.022634  0.016461  0.016461  0.028807  0.016461
1000  0.024550  0.028642  0.030278  0.031097  0.034370  0.043372  0.030278
5000  0.057107  0.046865  0.069522  0.068901  0.064246  0.072626  0.068901
           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000000  0.000000  0.000492  0.000000  0.000000  0.000492  0.000000
50    0.003414  0.000975  0.001463  0.000000  0.000000  0.003414  0.000488
100   0.004818  0.003373  0.005300  0.000482  0.000964  0.005782  0.000482
500   0.023731  0.023292  0.021973  0.008350  0.013184  0.019776  0.008789
1000  0.047911  0.041972  0.035637  0.023362  0.027717  0.036428  0.021778
5000  0.114683  0.121975  0.105624  0.110264  0.108938  0.104519  0.111590

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:45<00:00, 35.28s/it]

           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000757  0.000946  0.000189  0.000000  0.000189  0.001135  0.000000
50    0.002828  0.003959  0.002074  0.000566  0.001320  0.001885  0.000566
100   0.005441  0.006567  0.002627  0.000563  0.001689  0.005441  0.000563
500   0.025859  0.027306  0.013743  0.007414  0.010307  0.029114  0.007414
1000  0.052249  0.052595  0.025606  0.019031  0.021107  0.054671  0.019204
5000  0.191003  0.202571  0.123393  0.128535  0.127378  0.193702  0.129434

In [12]:
# Write P@k scores to Pkl
with open('scores-dump/all_pk_scores.pkl', 'wb') as file:
    pickle.dump(str(all_pk_scores), file)

# Write R@k scores to Pkl
with open('scores-dump/all_rk_scores.pkl', 'wb') as file:
    pickle.dump(str(all_rk_scores), file)

# Write F1@k scores to Pkl
with open('scores-dump/all_fk_scores.pkl', 'wb') as file:
    pickle.dump(str(all_fk_scores), file)

# Write RBO scores to Pkl
with open('scores-dump/all_rbo_scores.pkl', 'wb') as file:
    pickle.dump(str(all_rbo_scores), file)

In [48]:
# Calculate mean P@k scores and write to CSV
all_pk_scores_means = calc_score_means(all_pk_scores)
pd.DataFrame(all_pk_scores_means[0]).to_csv('table-4/table-4-all-pk-means.csv', index=False)
pd.DataFrame(all_pk_scores_means[1]).to_csv('table-4/table-4-amino_acid-pk-means.csv', index=False)
pd.DataFrame(all_pk_scores_means[2]).to_csv('table-4/table-4-nucleotide-pk-means.csv', index=False)
pd.DataFrame(all_pk_scores_means[3]).to_csv('table-4/table-4-multicell-pk-means.csv', index=False)
pd.DataFrame(all_pk_scores_means[4]).to_csv('table-4/table-4-cell-pk-means.csv', index=False)
pd.DataFrame(all_pk_scores_means[5]).to_csv('table-4/table-4-other-pk-means.csv', index=False)

# Calculate standard deviations for P@k scores and write to CSV
all_pk_scores_sds = calc_score_sds(all_pk_scores)
pd.DataFrame(all_pk_scores_sds[0]).to_csv('table-4/table-4-all-pk-sds.csv', index=False)
pd.DataFrame(all_pk_scores_sds[1]).to_csv('table-4/table-4-amino_acid-pk-sds.csv', index=False)
pd.DataFrame(all_pk_scores_sds[2]).to_csv('table-4/table-4-nucleotide-pk-sds.csv', index=False)
pd.DataFrame(all_pk_scores_sds[3]).to_csv('table-4/table-4-multicell-pk-sds.csv', index=False)
pd.DataFrame(all_pk_scores_sds[4]).to_csv('table-4/table-4-cell-pk-sds.csv', index=False)
pd.DataFrame(all_pk_scores_sds[5]).to_csv('table-4/table-4-other-pk-sds.csv', index=False)

In [49]:
# Display mean P@k scores and console
print("Mean P@k scores:")
with pd.option_context('display.precision', 4):
    display(all_pk_scores_means[0])
    display(all_pk_scores_means[1])
    display(all_pk_scores_means[2])
    display(all_pk_scores_means[3])
    display(all_pk_scores_means[4])
    display(all_pk_scores_means[5])

Mean P@k scores:

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.7667  0.8000  0.9000  1.0000  1.0000  0.9000  1.0000
50    0.8467  0.8867  0.9333  0.9600  1.0000  0.7667  1.0000
100   0.8633  0.8700  0.9433  0.9800  0.9800  0.7800  1.0000
500   0.8547  0.8460  0.9447  0.9833  0.9740  0.8253  0.9920
1000  0.8610  0.8453  0.9500  0.9817  0.9640  0.8537  0.9857
5000  0.8582  0.8474  0.9147  0.9277  0.8972  0.8753  0.9316

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.1667  0.2667  0.7000  1.0000  0.8000  0.1667  1.0000
50    0.2600  0.2733  0.5467  0.7533  0.7000  0.2133  0.7867
100   0.2933  0.2867  0.5300  0.8200  0.7467  0.1367  0.8300
500   0.2600  0.2533  0.5353  0.6873  0.6220  0.2200  0.6920
1000  0.2673  0.2460  0.5377  0.6397  0.5897  0.2527  0.6447
5000  0.2687  0.2426  0.4289  0.4281  0.4109  0.2800  0.4291

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.1333  0.1000  0.0667  0.0000  0.1000  0.0000  0.0000
50    0.1400  0.1333  0.0933  0.1000  0.1200  0.1200  0.1000
100   0.1400  0.1333  0.1100  0.1000  0.1000  0.1433  0.1100
500   0.1593  0.1520  0.1460  0.1433  0.1460  0.1367  0.1447
1000  0.1487  0.1537  0.1510  0.1320  0.1393  0.1400  0.1340
5000  0.1529  0.1554  0.1528  0.1546  0.1483  0.1528  0.1557

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.1000  0.0667  0.0000  0.0000  0.0000  0.0000  0.0000
50    0.0400  0.0400  0.0200  0.0400  0.0400  0.0800  0.0400
100   0.0300  0.0300  0.0367  0.0200  0.0200  0.0900  0.0200
500   0.0313  0.0393  0.0433  0.0333  0.0320  0.0560  0.0333
1000  0.0333  0.0377  0.0417  0.0370  0.0420  0.0530  0.0363
5000  0.0374  0.0347  0.0441  0.0444  0.0413  0.0468  0.0444

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0667  0.0667  0.1000  0.0000  0.0000  0.0667  0.0000
50    0.1067  0.1000  0.1133  0.0067  0.0000  0.1533  0.0133
100   0.0967  0.1100  0.1167  0.0100  0.0200  0.1200  0.0100
500   0.1167  0.1087  0.0887  0.0387  0.0600  0.0900  0.0380
1000  0.1220  0.1107  0.0850  0.0613  0.0697  0.0920  0.0590
5000  0.1091  0.1098  0.0954  0.1000  0.0986  0.0947  0.1008

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.3000  0.3000  0.0333  0.0000  0.1000  0.6667  0.0000
50    0.3000  0.3400  0.1600  0.0600  0.1400  0.2000  0.0600
100   0.3033  0.3100  0.1500  0.0300  0.0933  0.2900  0.0300
500   0.2873  0.2927  0.1313  0.0807  0.1140  0.3227  0.0840
1000  0.2897  0.2973  0.1347  0.1117  0.1233  0.3160  0.1117
5000  0.2902  0.3049  0.1935  0.2006  0.1981  0.3011  0.2016

In [17]:
# Displaye standard deviation of P@k scores to console
print("P@k scores standard deviations:")
with pd.option_context('display.precision', 4):
    display(all_pk_scores_sds[0])
    display(all_pk_scores_sds[1])
    display(all_pk_scores_sds[2])
    display(all_pk_scores_sds[3])
    display(all_pk_scores_sds[4])
    display(all_pk_scores_sds[5])

P@k scores standard deviations:

         IDF     ICF  Chi-sq          CG         ICB         DoP    RICF
10    0.1077  0.1192  0.0717  0.0000e+00  0.0000e+00  7.8107e-16  0.0000
50    0.0537  0.0462  0.0318  1.5621e-15  0.0000e+00  9.9514e-03  0.0000
100   0.0342  0.0331  0.0207  4.4633e-16  4.4633e-16  7.8107e-16  0.0000
500   0.0159  0.0145  0.0080  9.9676e-04  2.2316e-16  9.8862e-04  0.0009
1000  0.0114  0.0110  0.0049  1.7708e-03  1.0581e-03  4.6883e-04  0.0014
5000  0.0042  0.0042  0.0006  7.2288e-04  1.3052e-04  1.1192e-04  0.0003

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10    0.1452  0.1352  0.1536  0.0000e+00  1.5621e-15  4.6482e-02  0.0000e+00
50    0.0678  0.0553  0.0707  8.5847e-03  1.3390e-15  8.4591e-03  1.0048e-02
100   0.0458  0.0378  0.0463  1.2274e-15  5.0212e-03  3.6845e-03  1.2274e-15
500   0.0195  0.0191  0.0202  4.4485e-03  0.0000e+00  1.1158e-16  4.2211e-03
1000  0.0123  0.0131  0.0120  4.9247e-03  6.9660e-04  6.1266e-04  3.8599e-03
5000  0.0053  0.0057  0.0010  1.0892e-03  2.3132e-04  1.6783e-04  5.1591e-04

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10    0.1008  0.1148  0.1105  0.0000e+00  1.9527e-16  0.0000e+00  0.0000e+00
50    0.0530  0.0431  0.0501  1.9527e-16  1.9527e-16  1.9527e-16  1.9527e-16
100   0.0361  0.0357  0.0372  1.9527e-16  1.9527e-16  4.9889e-03  5.5791e-17
500   0.0159  0.0158  0.0156  2.7280e-03  3.3474e-16  6.7600e-04  2.8069e-03
1000  0.0107  0.0113  0.0089  3.1968e-03  5.0242e-04  7.1202e-04  2.8387e-03
5000  0.0046  0.0040  0.0008  7.7905e-04  9.8041e-05  2.0416e-04  3.1703e-04

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10    0.0569  0.0440  0.0572  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
50    0.0270  0.0247  0.0273  2.7895e-17  2.7895e-17  5.5791e-17  2.7895e-17
100   0.0192  0.0186  0.0164  1.3948e-17  1.3948e-17  8.3686e-17  1.3948e-17
500   0.0075  0.0075  0.0083  1.5277e-03  2.0922e-17  5.1286e-04  1.7146e-03
1000  0.0053  0.0053  0.0052  1.8297e-03  6.5897e-04  4.1843e-17  1.3437e-03
5000  0.0022  0.0023  0.0005  5.3068e-04  9.8041e-05  8.3686e-17  2.6285e-04

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10    0.0950  0.0985  0.0776  0.0000e+00  0.0000e+00  4.6057e-02  0.0000e+00
50    0.0409  0.0461  0.0420  8.5847e-03  0.0000e+00  8.0403e-03  1.0048e-02
100   0.0264  0.0342  0.0295  6.9739e-18  1.3948e-17  1.9527e-16  6.9739e-18
500   0.0155  0.0138  0.0107  2.2472e-03  9.7634e-17  8.3686e-17  2.5485e-03
1000  0.0102  0.0096  0.0069  2.4872e-03  7.3711e-04  5.5791e-17  1.8051e-03
5000  0.0044  0.0037  0.0005  6.9588e-04  1.4320e-04  9.5219e-05  3.5607e-04

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10    0.1438  0.1423  0.1044  0.0000e+00  1.9527e-16  5.4855e-02  0.0000e+00
50    0.0632  0.0673  0.0471  9.7634e-17  1.6737e-16  3.9054e-16  9.7634e-17
100   0.0438  0.0493  0.0317  4.8817e-17  5.0212e-03  4.9237e-03  4.8817e-17
500   0.0190  0.0200  0.0135  2.3719e-03  1.8132e-16  9.8041e-04  2.7012e-03
1000  0.0122  0.0140  0.0086  3.6145e-03  6.2109e-04  6.6203e-04  2.9404e-03
5000  0.0051  0.0062  0.0010  1.1052e-03  2.4960e-04  1.9258e-04  4.3001e-04

In [50]:
# Calculate mean R@k scores and write to CSV
all_rk_scores_means = calc_score_means(all_rk_scores)
pd.DataFrame(all_rk_scores_means[0]).to_csv('table-4/table-4-all-rk-means.csv', index=False)
pd.DataFrame(all_rk_scores_means[1]).to_csv('table-4/table-4-amino_acid-rk-means.csv', index=False)
pd.DataFrame(all_rk_scores_means[2]).to_csv('table-4/table-4-nucleotide-rk-means.csv', index=False)
pd.DataFrame(all_rk_scores_means[3]).to_csv('table-4/table-4-multicell-rk-means.csv', index=False)
pd.DataFrame(all_rk_scores_means[4]).to_csv('table-4/table-4-cell-rk-means.csv', index=False)
pd.DataFrame(all_rk_scores_means[5]).to_csv('table-4/table-4-other-rk-means.csv', index=False)

# Calculate standard deviations for R@k scores and write to CSV
all_rk_scores_sds = calc_score_sds(all_rk_scores)
pd.DataFrame(all_rk_scores_sds[0]).to_csv('table-4/table-4-all-rk-sds.csv', index=False)
pd.DataFrame(all_rk_scores_sds[1]).to_csv('table-4/table-4-amino_acid-rk-sds.csv', index=False)
pd.DataFrame(all_rk_scores_sds[2]).to_csv('table-4/table-4-nucleotide-rk-sds.csv', index=False)
pd.DataFrame(all_rk_scores_sds[3]).to_csv('table-4/table-4-multicell-rk-sds.csv', index=False)
pd.DataFrame(all_rk_scores_sds[4]).to_csv('table-4/table-4-cell-rk-sds.csv', index=False)
pd.DataFrame(all_rk_scores_sds[5]).to_csv('table-4/table-4-other-rk-sds.csv', index=False)

In [51]:
# Display mean R@k scores console
print("Mean R@k scores:")
with pd.option_context('display.precision', 4):
    display(all_rk_scores_means[0])
    display(all_rk_scores_means[1])
    display(all_rk_scores_means[2])
    display(all_rk_scores_means[3])
    display(all_rk_scores_means[4])
    display(all_rk_scores_means[5])

Mean R@k scores:

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0002  0.0003  0.0003  0.0003  0.0003  0.0003  0.0003
50    0.0013  0.0014  0.0015  0.0015  0.0016  0.0012  0.0016
100   0.0027  0.0027  0.0030  0.0031  0.0031  0.0025  0.0031
500   0.0134  0.0133  0.0149  0.0155  0.0153  0.0130  0.0156
1000  0.0271  0.0266  0.0299  0.0309  0.0303  0.0269  0.0310
5000  0.1350  0.1333  0.1439  0.1459  0.1411  0.1377  0.1465

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0002  0.0003  0.0007  0.0010  0.0008  0.0002  0.0010
50    0.0013  0.0013  0.0027  0.0037  0.0034  0.0011  0.0039
100   0.0029  0.0028  0.0052  0.0081  0.0074  0.0013  0.0082
500   0.0128  0.0125  0.0264  0.0338  0.0306  0.0108  0.0341
1000  0.0263  0.0242  0.0529  0.0630  0.0581  0.0249  0.0635
5000  0.1323  0.1194  0.2112  0.2108  0.2023  0.1379  0.2113

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0002  0.0002  0.0001  0.0000  0.0002  0.0000  0.0000
50    0.0013  0.0012  0.0008  0.0009  0.0011  0.0011  0.0009
100   0.0025  0.0024  0.0020  0.0018  0.0018  0.0026  0.0020
500   0.0143  0.0136  0.0131  0.0129  0.0131  0.0123  0.0130
1000  0.0267  0.0276  0.0271  0.0237  0.0250  0.0251  0.0240
5000  0.1371  0.1394  0.1371  0.1387  0.1330  0.1371  0.1397

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0007  0.0005  0.0000  0.0000  0.0000  0.0000  0.0000
50    0.0014  0.0014  0.0007  0.0014  0.0014  0.0028  0.0014
100   0.0021  0.0021  0.0025  0.0014  0.0014  0.0062  0.0014
500   0.0108  0.0136  0.0150  0.0115  0.0111  0.0194  0.0115
1000  0.0231  0.0261  0.0289  0.0256  0.0291  0.0367  0.0252
5000  0.1295  0.1203  0.1528  0.1537  0.1431  0.1620  0.1537

         IDF     ICF  Chi-sq          CG     ICB     DoP    RICF
10    0.0002  0.0002  0.0002  0.0000e+00  0.0000  0.0002  0.0000
50    0.0013  0.0012  0.0014  8.2284e-05  0.0000  0.0019  0.0002
100   0.0024  0.0027  0.0029  2.4685e-04  0.0005  0.0030  0.0002
500   0.0144  0.0134  0.0109  4.7725e-03  0.0074  0.0111  0.0047
1000  0.0301  0.0273  0.0210  1.5140e-02  0.0172  0.0227  0.0146
5000  0.1346  0.1355  0.1177  1.2343e-01  0.1217  0.1168  0.1244

         IDF     ICF      Chi-sq      CG         ICB     DoP    RICF
10    0.0003  0.0003  3.1566e-05  0.0000  9.4697e-05  0.0006  0.0000
50    0.0014  0.0016  7.5758e-04  0.0003  6.6288e-04  0.0009  0.0003
100   0.0029  0.0029  1.4205e-03  0.0003  8.8384e-04  0.0027  0.0003
500   0.0136  0.0139  6.2184e-03  0.0038  5.3977e-03  0.0153  0.0040
1000  0.0274  0.0282  1.2753e-02  0.0106  1.1679e-02  0.0299  0.0106
5000  0.1374  0.1443  9.1604e-02  0.0950  9.3782e-02  0.1426  0.0955

In [21]:
# Display standard deviation of R@k scores to console
print("R@k scores standard deviations:")
with pd.option_context('display.precision', 4):
    display(all_rk_scores_sds[0])
    display(all_rk_scores_sds[1])
    display(all_rk_scores_sds[2])
    display(all_rk_scores_sds[3])
    display(all_rk_scores_sds[4])
    display(all_rk_scores_sds[5])

R@k scores standard deviations:

,IDF,ICF,Chi-sq,CG,ICB,DoP,RICF
10,3.3870e-05,3.7512e-05,2.2571e-05,5.9932e-19,5.9932e-19,2.7242e-19,5.9932e-19
50,8.4497e-05,7.2715e-05,5.0092e-05,3.9228e-18,2.1793e-19,1.5653e-05,2.1793e-19
100,1.0773e-04,1.0400e-04,6.5206e-05,2.1793e-18,2.1793e-18,0.0000e+00,4.3587e-19
500,2.5046e-04,2.2745e-04,1.2648e-04,1.5679e-05,6.9739e-18,1.5551e-05,1.4347e-05
1000,3.5761e-04,3.4616e-04,1.5260e-04,5.5709e-05,3.3287e-05,1.4749e-05,4.2931e-05
5000,6.5318e-04,6.5395e-04,9.8881e-05,1.1371e-04,2.0530e-05,1.7604e-05,5.4466e-05

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10    0.0001  0.0001  0.0002  1.0897e-18  0.0000e+00  4.5773e-05  1.0897e-18
50    0.0003  0.0003  0.0003  4.2268e-05  1.7435e-18  4.1650e-05  4.9475e-05
100   0.0005  0.0004  0.0005  8.7173e-18  4.9445e-05  3.6283e-05  1.0461e-17
500   0.0010  0.0009  0.0010  2.1903e-04  3.4869e-17  2.0922e-17  2.0783e-04
1000  0.0012  0.0013  0.0012  4.8495e-04  6.8597e-05  6.0331e-05  3.8010e-04
5000  0.0026  0.0028  0.0005  5.3627e-04  1.1390e-04  8.2632e-05  2.5402e-04

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10    0.0002  0.0002  0.0002  0.0000e+00  8.1725e-20  0.0000e+00  0.0000e+00
50    0.0005  0.0004  0.0004  2.1793e-19  1.9614e-18  1.9614e-18  2.1793e-19
100   0.0006  0.0006  0.0007  4.3587e-19  4.3587e-19  8.9503e-05  8.7173e-19
500   0.0014  0.0014  0.0014  2.4471e-04  1.9178e-17  6.0638e-05  2.5179e-04
1000  0.0019  0.0020  0.0016  5.7351e-04  9.0136e-05  1.2774e-04  5.0928e-04
5000  0.0042  0.0036  0.0007  6.9882e-04  8.7945e-05  1.8313e-04  2.8438e-04

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10    0.0004  0.0003  0.0004  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
50    0.0009  0.0009  0.0009  6.5380e-19  6.5380e-19  1.3076e-18  6.5380e-19
100   0.0013  0.0013  0.0011  6.5380e-19  6.5380e-19  3.4869e-18  6.5380e-19
500   0.0026  0.0026  0.0029  5.2897e-04  5.2304e-18  1.7758e-04  5.9369e-04
1000  0.0037  0.0037  0.0036  1.2671e-03  4.5635e-04  2.7895e-17  9.3055e-04
5000  0.0076  0.0080  0.0017  1.8375e-03  3.3948e-04  8.3686e-17  9.1015e-04

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10    0.0002  0.0002  0.0002  0.0000e+00  0.0000e+00  1.1369e-04  0.0000e+00
50    0.0005  0.0006  0.0005  1.0596e-04  0.0000e+00  9.9238e-05  1.2402e-04
100   0.0007  0.0008  0.0007  1.6345e-19  3.2690e-19  2.1793e-18  1.6345e-19
500   0.0019  0.0017  0.0013  2.7737e-04  6.1021e-18  8.7173e-18  3.1455e-04
1000  0.0025  0.0024  0.0017  6.1398e-04  1.8196e-04  1.7435e-17  4.4560e-04
5000  0.0054  0.0046  0.0007  8.5890e-04  1.7674e-04  1.1753e-04  4.3948e-04

,IDF,ICF,Chi-sq,CG,ICB,DoP,RICF
10,0.0001,0.0001,9.8908e-05,0.0000e+00,4.0862e-20,5.1946e-05,0.0000e+00
50,0.0003,0.0003,2.2306e-04,7.0828e-19,2.1793e-19,7.6276e-19,7.0828e-19
100,0.0004,0.0005,3.0048e-04,7.0828e-19,4.7549e-05,4.6626e-05,7.0828e-19
500,0.0009,0.0009,6.3822e-04,1.1231e-04,1.1333e-17,4.6421e-05,1.2790e-04
1000,0.0012,0.0013,8.1154e-04,3.4228e-04,5.8816e-05,6.2692e-05,2.7845e-04
5000,0.0024,0.0030,4.5865e-04,5.2328e-04,1.1818e-04,9.1183e-05,2.0360e-04

In [52]:
# Calculate mean F1@k scores and write to CSV
all_fk_scores_means = calc_score_means(all_fk_scores)
pd.DataFrame(all_fk_scores_means[0]).to_csv('table-4/table-4-all-fk-means.csv', index=False)
pd.DataFrame(all_fk_scores_means[1]).to_csv('table-4/table-4-amino_acid-fk-means.csv', index=False)
pd.DataFrame(all_fk_scores_means[2]).to_csv('table-4/table-4-nucleotide-fk-means.csv', index=False)
pd.DataFrame(all_fk_scores_means[3]).to_csv('table-4/table-4-multicell-fk-means.csv', index=False)
pd.DataFrame(all_fk_scores_means[4]).to_csv('table-4/table-4-cell-fk-means.csv', index=False)
pd.DataFrame(all_fk_scores_means[5]).to_csv('table-4/table-4-other-fk-means.csv', index=False)

# Calculate standard deviations for F1@k scores and write to CSV
all_fk_scores_sds = calc_score_sds(all_fk_scores)
pd.DataFrame(all_fk_scores_sds[0]).to_csv('table-4/table-4-all-fk-sds.csv', index=False)
pd.DataFrame(all_fk_scores_sds[1]).to_csv('table-4/table-4-amino_acid-fk-sds.csv', index=False)
pd.DataFrame(all_fk_scores_sds[2]).to_csv('table-4/table-4-nucleotide-fk-sds.csv', index=False)
pd.DataFrame(all_fk_scores_sds[3]).to_csv('table-4/table-4-multicell-fk-sds.csv', index=False)
pd.DataFrame(all_fk_scores_sds[4]).to_csv('table-4/table-4-cell-fk-sds.csv', index=False)
pd.DataFrame(all_fk_scores_sds[5]).to_csv('table-4/table-4-other-fk-sds.csv', index=False)

In [55]:
print(all_fk_scores_means)

[           IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000482  0.000503  0.000566  0.000629  0.000629  0.000566  0.000629
50    0.002659  0.002785  0.002932  0.003015  0.003141  0.002408  0.003141
100   0.005415  0.005457  0.005917  0.006147  0.006147  0.004892  0.006272
500   0.026471  0.026202  0.029258  0.030456  0.030167  0.025562  0.030724
1000  0.052521  0.051565  0.057950  0.059881  0.058804  0.052073  0.060125
5000  0.233289  0.230353  0.248657  0.252191  0.243891  0.237946  0.253242,            IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000328  0.000525  0.001377  0.001968  0.001574  0.000328  0.001968
50    0.002548  0.002678  0.005357  0.007382  0.006859  0.002090  0.007709
100   0.005721  0.005591  0.010336  0.015992  0.014562  0.002665  0.016187
500   0.024402  0.023776  0.050242  0.064508  0.058376  0.020648  0.064946
1000  0.047931  0.044106  0.096399  0.114687  0.105722  0.045301  0.115583
5000  0.177279  0.160079  0.283031  0.282503  0.271154  0.184758  0.283119,            IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000478  0.000358  0.000239  0.000000  0.000358  0.000000  0.000000
50    0.002489  0.002371  0.001660  0.001778  0.002134  0.002134  0.001778
100   0.004935  0.004700  0.003877  0.003525  0.003525  0.005052  0.003877
500   0.026232  0.025025  0.024037  0.023598  0.024037  0.022500  0.023817
1000  0.045229  0.046750  0.045939  0.040158  0.042389  0.042592  0.040767
5000  0.144568  0.146964  0.144505  0.146208  0.140218  0.144505  0.147279,            IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.001376  0.000917  0.000000  0.000000  0.000000  0.000000  0.000000
50    0.002677  0.002677  0.001339  0.002677  0.002677  0.005355  0.002677
100   0.003886  0.003886  0.004750  0.002591  0.002591  0.011658  0.002591
500   0.016118  0.020233  0.022291  0.017147  0.016461  0.028807  0.017147
1000  0.027278  0.030824  0.034097  0.030278  0.034370  0.043372  0.029733
5000  0.058038  0.053900  0.068487  0.068901  0.064142  0.072626  0.068901,            IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000328  0.000328  0.000492  0.000000  0.000000  0.000328  0.000000
50    0.002601  0.002438  0.002764  0.000163  0.000000  0.003739  0.000325
100   0.004658  0.005300  0.005621  0.000482  0.000964  0.005782  0.000482
500   0.025635  0.023878  0.019483  0.008496  0.013184  0.019776  0.008350
1000  0.048307  0.043820  0.033657  0.024286  0.027585  0.036428  0.023362
5000  0.120502  0.121313  0.105403  0.110485  0.108938  0.104592  0.111369,            IDF       ICF    Chi-sq        CG       ICB       DoP      RICF
10    0.000568  0.000568  0.000063  0.000000  0.000189  0.001261  0.000000
50    0.002828  0.003205  0.001508  0.000566  0.001320  0.001885  0.000566
100   0.005691  0.005816  0.002814  0.000563  0.001751  0.005441  0.000563
500   0.025980  0.026462  0.011875  0.007294  0.010307  0.029174  0.007595
1000  0.050115  0.051442  0.023299  0.019319  0.021338  0.054671  0.019319
5000  0.186504  0.195930  0.124336  0.128920  0.127292  0.193488  0.129563]

In [56]:
# Display mean F1@k scores to console
print("Mean F1@k scores:")
with pd.option_context('display.precision', 4):
    display(all_fk_scores_means[0])
    display(all_fk_scores_means[1])
    display(all_fk_scores_means[2])
    display(all_fk_scores_means[3])
    display(all_fk_scores_means[4])
    display(all_fk_scores_means[5])

Mean F1@k scores:

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0005  0.0005  0.0006  0.0006  0.0006  0.0006  0.0006
50    0.0027  0.0028  0.0029  0.0030  0.0031  0.0024  0.0031
100   0.0054  0.0055  0.0059  0.0061  0.0061  0.0049  0.0063
500   0.0265  0.0262  0.0293  0.0305  0.0302  0.0256  0.0307
1000  0.0525  0.0516  0.0579  0.0599  0.0588  0.0521  0.0601
5000  0.2333  0.2304  0.2487  0.2522  0.2439  0.2379  0.2532

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0003  0.0005  0.0014  0.0020  0.0016  0.0003  0.0020
50    0.0025  0.0027  0.0054  0.0074  0.0069  0.0021  0.0077
100   0.0057  0.0056  0.0103  0.0160  0.0146  0.0027  0.0162
500   0.0244  0.0238  0.0502  0.0645  0.0584  0.0206  0.0649
1000  0.0479  0.0441  0.0964  0.1147  0.1057  0.0453  0.1156
5000  0.1773  0.1601  0.2830  0.2825  0.2712  0.1848  0.2831

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0005  0.0004  0.0002  0.0000  0.0004  0.0000  0.0000
50    0.0025  0.0024  0.0017  0.0018  0.0021  0.0021  0.0018
100   0.0049  0.0047  0.0039  0.0035  0.0035  0.0051  0.0039
500   0.0262  0.0250  0.0240  0.0236  0.0240  0.0225  0.0238
1000  0.0452  0.0467  0.0459  0.0402  0.0424  0.0426  0.0408
5000  0.1446  0.1470  0.1445  0.1462  0.1402  0.1445  0.1473

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0014  0.0009  0.0000  0.0000  0.0000  0.0000  0.0000
50    0.0027  0.0027  0.0013  0.0027  0.0027  0.0054  0.0027
100   0.0039  0.0039  0.0047  0.0026  0.0026  0.0117  0.0026
500   0.0161  0.0202  0.0223  0.0171  0.0165  0.0288  0.0171
1000  0.0273  0.0308  0.0341  0.0303  0.0344  0.0434  0.0297
5000  0.0580  0.0539  0.0685  0.0689  0.0641  0.0726  0.0689

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0003  0.0003  0.0005  0.0000  0.0000  0.0003  0.0000
50    0.0026  0.0024  0.0028  0.0002  0.0000  0.0037  0.0003
100   0.0047  0.0053  0.0056  0.0005  0.0010  0.0058  0.0005
500   0.0256  0.0239  0.0195  0.0085  0.0132  0.0198  0.0083
1000  0.0483  0.0438  0.0337  0.0243  0.0276  0.0364  0.0234
5000  0.1205  0.1213  0.1054  0.1105  0.1089  0.1046  0.1114

         IDF     ICF      Chi-sq      CG     ICB     DoP    RICF
10    0.0006  0.0006  6.3072e-05  0.0000  0.0002  0.0013  0.0000
50    0.0028  0.0032  1.5080e-03  0.0006  0.0013  0.0019  0.0006
100   0.0057  0.0058  2.8143e-03  0.0006  0.0018  0.0054  0.0006
500   0.0260  0.0265  1.1875e-02  0.0073  0.0103  0.0292  0.0076
1000  0.0501  0.0514  2.3299e-02  0.0193  0.0213  0.0547  0.0193
5000  0.1865  0.1959  1.2434e-01  0.1289  0.1273  0.1935  0.1296

In [24]:
# Display standard deviation of F1@k scores to console
print("F1@k scores standard deviations:")
with pd.option_context('display.precision', 4):
    display(all_fk_scores_sds[0])
    display(all_fk_scores_sds[1])
    display(all_fk_scores_sds[2])
    display(all_fk_scores_sds[3])
    display(all_fk_scores_sds[4])
    display(all_fk_scores_sds[5])

F1@k scores standard deviations:

,IDF,ICF,Chi-sq,CG,ICB,DoP,RICF
10,6.7718e-05,7.5001e-05,4.5127e-05,6.5380e-19,6.5380e-19,7.6276e-19,6.5380e-19
50,1.6873e-04,1.4520e-04,1.0003e-04,2.1793e-18,5.6663e-18,3.1257e-05,5.6663e-18
100,2.1479e-04,2.0735e-04,1.3000e-04,8.7173e-19,8.7173e-19,1.1333e-17,3.4869e-18
500,4.9316e-04,4.4786e-04,2.4903e-04,3.0872e-05,5.2304e-17,3.0620e-05,2.8250e-05
1000,6.9341e-04,6.7120e-04,2.9589e-04,1.0802e-04,6.4544e-05,2.8598e-05,8.3242e-05
5000,1.1288e-03,1.1301e-03,1.7088e-04,1.9650e-04,3.5479e-05,3.0423e-05,9.4127e-05

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10       NaN     NaN  0.0003  2.6152e-18  2.3973e-18  9.1456e-05  2.6152e-18
50    0.0007  0.0005  0.0007  8.4122e-05  3.4869e-18  8.2891e-05  9.8465e-05
100   0.0009  0.0007  0.0009  1.7435e-17  9.7926e-05  7.1858e-05  1.7435e-17
500   0.0018  0.0018  0.0019  4.1751e-04  1.3948e-17  2.7895e-17  3.9616e-04
1000  0.0022  0.0023  0.0022  8.8296e-04  1.2489e-04  1.0985e-04  6.9205e-04
5000  0.0035  0.0038  0.0006  7.1868e-04  1.5264e-04  1.1074e-04  3.4042e-04

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10       NaN     NaN     NaN         NaN  4.9035e-19         NaN         NaN
50    0.0009  0.0008  0.0009  3.9228e-18  2.6152e-18  2.6152e-18  3.9228e-18
100   0.0013  0.0013  0.0013  3.4869e-18  3.4869e-18  1.7585e-04  2.6152e-18
500   0.0026  0.0026  0.0026  4.4913e-04  3.4869e-18  1.1129e-04  4.6212e-04
1000  0.0033  0.0034  0.0027  9.7255e-04  1.5285e-04  2.1662e-04  8.6363e-04
5000  0.0044  0.0038  0.0007  7.3676e-04  9.2719e-05  1.9308e-04  2.9982e-04

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10       NaN     NaN     NaN         NaN         NaN         NaN         NaN
50       NaN     NaN     NaN  1.7435e-18  1.7435e-18  3.4869e-18  1.7435e-18
100      NaN     NaN     NaN  3.4869e-18  3.4869e-18  1.9178e-17  3.4869e-18
500   0.0039  0.0039  0.0043  7.8583e-04  2.4408e-17  2.6382e-04  8.8199e-04
1000  0.0044  0.0043  0.0042  1.4973e-03  5.3926e-04  3.4869e-17  1.0996e-03
5000  0.0034  0.0036  0.0008  8.2352e-04  1.5214e-04  5.5791e-17  4.0790e-04

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10       NaN     NaN     NaN         NaN         NaN         NaN         NaN
50    0.0010  0.0011     NaN         NaN         NaN  1.9606e-04         NaN
100   0.0013  0.0016  0.0014  9.8070e-19  1.9614e-18  6.1021e-18  9.8070e-19
500   0.0034  0.0030  0.0024  4.9379e-04  0.0000e+00  1.0461e-17  5.5999e-04
1000  0.0040  0.0038  0.0027  9.8484e-04  2.9187e-04  0.0000e+00  7.1476e-04
5000  0.0049  0.0041  0.0006  7.6884e-04  1.5821e-04  1.0520e-04  3.9340e-04

         IDF     ICF  Chi-sq          CG         ICB         DoP        RICF
10       NaN     NaN     NaN         NaN  4.9035e-19  1.0379e-04         NaN
50    0.0006  0.0006  0.0004  6.5380e-19  1.0897e-18  2.1793e-18  6.5380e-19
100   0.0008  0.0009  0.0006  7.6276e-19  9.4206e-05  9.2376e-05  7.6276e-19
500   0.0017  0.0018  0.0012  2.1446e-04  6.9739e-18  8.8645e-05  2.4423e-04
1000  0.0021  0.0024  0.0015  6.2534e-04  1.0746e-04  1.1454e-04  5.0872e-04
5000  0.0033  0.0040  0.0006  7.1026e-04  1.6041e-04  1.2377e-04  2.7635e-04

In [26]:
# Calculate mean RBO scores and display to console
mean_rbo_scores = calc_mean_rbo_scores(all_rbo_scores)
  
with pd.option_context('display.precision', 4):
    display(mean_rbo_scores)

         IDF  ICF  Chi-sq      CG     ICB     DoP  RICF
10    0.0000  0.0  0.0010  0.9123  0.6134  0.0000   1.0
50    0.0003  0.0  0.0084  0.8988  0.6886  0.0000   1.0
100   0.0010  0.0  0.0186  0.9078  0.7028  0.0000   1.0
500   0.0068  0.0  0.0993  0.9309  0.7288  0.0005   1.0
1000  0.0125  0.0  0.1985  0.9354  0.7656  0.0031   1.0
5000  0.0603  0.0  0.6531  0.9066  0.7956  0.0431   1.0

## Top 10 Ranked Terms Example

Here we reproduce the result of Table 5 from the manuscript.

In [23]:
# Initialize a random seed to ensure results can be replicated
np.random.seed(641369)

In [ ]:
ranked_terms_df = resort(term_scores_df)
top_10_ranked_terms_df = pd.DataFrame(top_k(ranked_terms_df, 10))
display(top_10_ranked_terms_df)

In [25]:
# Write to CSV
top_10_ranked_terms_df.to_csv('table-5/table-5.csv', index=False)

## Stopwords Exploratory Analysis

Here we reproduce the result of Table 6 from the manuscript.

In [ ]:
import pandas as pd
from nltk.corpus import stopwords

# Ensure you have the stopwords downloaded
import nltk
nltk.download('stopwords')

def getrank(sorted_measures):
    unique_terms = set()
    for terms in sorted_measures.values():
        unique_terms.update(terms)
    unique_terms = sorted(unique_terms)
    
    # Create a data frame to hold the rankings
    ranking_df = pd.DataFrame(index=unique_terms, columns=sorted_measures.keys())
    
    # Fill the data frame with rankings
    for measure, terms in sorted_measures.items():
        for rank, term in enumerate(terms):
            ranking_df.at[term, measure] = rank + 1  # Rank starts from 1
    
    # Replace NaN with a large number to indicate unranked terms
    ranking_df = ranking_df.fillna(len(unique_terms) + 1)
    #csv_file_path = 'ranking_table.csv'
    #ranking_df.to_csv(csv_file_path)
    return ranking_df

# Function to filter stopwords from the ranking data frame
def filter_stopwords(ranking_df):
    stopwords_list = set(stopwords.words('english'))
    
    # Filter the data frame to include only stopwords
    stopwords_rank = ranking_df[ranking_df.index.isin(stopwords_list)]
    
    # Save the stopwords ranking data frame to a CSV file
    #csv_file_path = 'stopwords_ranking_table.csv'
    #stopwords_rank.to_csv(csv_file_path)
    
    return stopwords_rank

In [ ]:
# Initialize a random seed to ensure results can be replicated
np.random.seed(641369)

# Generate term dispersion ranks for R different versions of the data
R = 100
all_quantiles_df = []
for r in tqdm(range(R)):
    sorted_measures = resort(term_scores_df)
    rank = getrank(sorted_measures)
    stopwords_ranks_df = filter_stopwords(rank)
    bursty_measure_names = stopwords_ranks_df.head(0)
    quantiles = []
    for bursty_measure_name in bursty_measure_names:
        quantiles.append(stopwords_ranks_df[bursty_measure_name].quantile([0, 0.25, 0.5, 0.75, 1]))
    quantiles_df = pd.DataFrame(quantiles)
    all_quantiles_df.append(quantiles_df)

In [28]:
# Extract the column and index names from the first quantiles data frame
columns = all_quantiles_df[0].columns
index = all_quantiles_df[0].index

# Initialize empty data frames to store the mean and standard deviation values
mean_df = pd.DataFrame(index=index, columns=columns)
std_df = pd.DataFrame(index=index, columns=columns)

# Compute the mean and standard deviation of corresponding elements across all matrices
for col in columns:
    for idx in index:
        values = [matrix.at[idx, col] for matrix in all_quantiles_df]
        mean_df.at[idx, col] = np.mean(values)
        std_df.at[idx, col] = np.std(values)

In [ ]:
# Display the resulting data frames
print("Mean values:")
with pd.option_context('display.precision', 4):
    display(mean_df)
print("\nStandard deviations:")
with pd.option_context('display.precision', 4):
    display(std_df)

In [30]:
# Write to CSV
mean_df.to_csv('table-6/table-6-means.csv')
std_df.to_csv('table-6/table-6-sds.csv')