# Evaluate Term Dispersion Scores on the GENIA Corpus Data and Reproduce Results Reported in the Mannuscript 

Authors: Samuel Sarria Hurtado, Uyen "Rachel" Lai, and Paul Sheridan

Last update: 2025-06-03

Description: Evaluate the following term dispersion scores on the Genia corpus data:
- Inverse Document Frequency (IDF)
- Inverse Collection Frequency (ICF)
- Chi-square
- Church and Gale (CG)
- Irvine and Callison-Burch (ICB)
- Derivation of Proportions (DoP)
- Residual ICF (RICF)

Calculate average P@k scores for each scoring function using the GENIA terms as ground truth. Also, evaluate scoring functions for their ability to filter out stopwords.

## Preliminaries

In [1]:
# Imports
import sys
import os
import pickle
import json
import pandas as pd
sys.path.append('../0-base-functions/')
import wordstats
from sklearn.feature_extraction.text import CountVectorizer
import random
import numpy as np
import scipy
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from io import StringIO
from numpy import nan
from tqdm import tqdm
import rbo

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/pasheridan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

## Load the GENIA Corpus Data

In particular, we load the
- preprocessed GENIA corpus documents,
- and gold standard biological terms (i.e., lexical units) and their associated semantic classes (i.e., sems).

In [3]:
# Load the preprocessed GENIA corpus documents
genia_corpus_path = '../1-preprocessing/GENIAcorpus3.02-preprocessed.json'

with open(genia_corpus_path, "r") as j:
  genia_corpus = json.loads(j.read())

# Load gold standard terms 
genia_keywords_path = '../1-preprocessing/GENIAcorpus3.02-keywords.tsv'

with open(genia_keywords_path, "r") as c:
  genia_lexical_units_and_sems = pd.read_csv(c, sep='\t')

genia_lexical_units = genia_lexical_units_and_sems.lex.to_numpy()

## Prepare the GENIA Corpus Data for Analysis

Prepare the corpus vocabulary.

In [4]:
# Compile the GENIA corpus vocabulary
pre_vocab = []
for i in range(len(genia_corpus)):
  pre_vocab.append(genia_corpus[i].split())

vocab = []
for i in range(len(pre_vocab)):
  for j in range(len(pre_vocab[i])):
    vocab.append(pre_vocab[i][j])

vocab = list(set(vocab))
vocab.sort()

Convert GENIA documents into term-in-document matrix of token counts.

In [5]:
# Helper function to ensure that CountVectorizer doesn't ignore any terms
def analyzer_custom(doc):
  return doc.split()

# Generate term-in-document counts
counter = CountVectorizer(lowercase=False, vocabulary=vocab, analyzer=analyzer_custom)
collection = counter.transform(genia_corpus)

## Evaluate Term Dispersion Scores for Selected Measures

Calculate bag-of-words model word statistics and related quantities.

In [6]:
# Calculate word statistics and related quantities
m = len(counter.get_feature_names_out()) # vocab size
d = collection.shape[0] # collection size
N_i = wordstats.get_Ni(collection)
N_j = wordstats.get_Nj(collection)
N = wordstats.get_N(N_j)
B_ij = wordstats.get_Bij(collection)
B_i = wordstats.get_Bi(B_ij)
B_j = wordstats.get_Bj(B_ij)
DF = wordstats.get_DF(B_i, d)
CF = wordstats.get_CF(N_i)
nij_by_nj = wordstats.get_nij_by_nj(collection, N_j)
thetas = np.array(range(1, max(N_i.A[0]) + 1))/N
opt_thetas = wordstats.get_opt_thetas(N, m, d, N_i, N_j, B_i, thetas)

Evaluate term dispersion scores.

In [7]:
# Calculate word dispersion scores according the various measures used in this study
IDF = wordstats.get_IDF(DF)
ICF = wordstats.get_ICF(CF)
Chisq = wordstats.get_Chisq(collection)
CG = wordstats.get_CG(N_i, B_i)
ICB = wordstats.get_ICB(nij_by_nj, B_i)
DoP = wordstats.get_DoP(collection, N_i, N_j, N)
RICF = wordstats.get_RICF(opt_thetas, N, ICF)

/Users/pasheridan/Desktop/bursty-term-measure/genia/3-tables/../0-base-functions/wordstats.py:209: RuntimeWarning: divide by zero encountered in log
  return -np.log(chisq_values)

Arrange term dispersion scores into a data frame.

In [8]:
# Initialize dispersion scores data frame
term_scores_df = pd.DataFrame(data=
                         {'term': counter.get_feature_names_out(),
                          'IDF': IDF.A[0],
                          'ICF': ICF.A[0],
                          'Chi-sq': Chisq,
                          'CG': CG.A[0],
                          'ICB': ICB.A[0],
                          'DoP': DoP.A[0],
                          'RICF': RICF.A[0]})

# Print term dispersion scores to console
display(term_scores_df)

# Write to TSV
term_scores_df.to_csv('term-dispersion-scores.tsv', sep='\t')

,term,IDF,ICF,Chi-sq,CG,ICB,DoP,RICF
0,'aged'_lymphocyte_lex,7.600902,12.800954,0.701595,1.0,244.0,-0.000673,-0.000251
1,'converted'_TCEd_motif_lex,7.600902,12.800954,0.701595,1.0,195.0,-0.000538,-0.000251
2,'latency_I'_lex,7.600902,12.800954,0.701595,1.0,206.0,-0.000568,-0.000251
3,'latency_II'_lex,7.600902,12.800954,0.701595,1.0,206.0,-0.000568,-0.000251
4,'master_regulator_lex,7.600902,12.800954,0.701595,1.0,63.0,-0.000174,-0.000251
...,...,...,...,...,...,...,...,...
40799,zymogen_plasma_factor_X_lex,7.600902,12.800954,0.701595,1.0,355.0,-0.000979,-0.000251
40800,zymogen_plasma_factors_VII_lex,7.600902,12.800954,0.701595,1.0,355.0,-0.000979,-0.000251
40801,zymography_lex,7.600902,12.800954,0.701595,1.0,191.0,-0.000527,-0.000251
40802,zymosan-treated_cell_lex,7.600902,12.800954,0.701595,1.0,225.0,-0.000621,-0.000251
40803,zymosan_lex,6.907755,11.414659,587.746183,2.0,458.0,-0.001285,0.692615

## Compile GENIA Corpus Summary Statistics

This is the result of Table 3 from the manuscript.

In [9]:
# Collect lexical units belonging to a given high-level semantic class
def get_high_level_semantic_class_words(high_level_class_lst):
  words = []
  for k, v in lex_sem_dct.items():
    if v in high_level_class_lst:
      words.append(k)
  return words

# Hardcode the semantic classes according to their high-level designations.
amino_acid_sems = ['G#amino_acid_monomer', 'G#peptide', 'G#protein_N/A',
              'G#protein_complex', 'G#protein_domain_or_region',
              'G#protein_family_or_group', 'G#protein_molecule',
              'G#protein_substructure', 'G#protein_subunit',
              'G#other_organic_compound', 'G#organic', 'G#inorganic', 'G#atom',
              'G#carbohydrate', 'G#lipid']
nucleotide_sems = ['G#nucleotide', 'G#polynucleotide', 'G#DNA_N/A',
        'G#DNA_domain_or_region', 'G#DNA_family_or_group', 'G#DNA_molecule',
        'G#DNA_substructure', 'G#RNA_N/A', 'G#RNA_domain_or_region',
        'G#RNA_family_or_group', 'G#RNA_molecule', 'G#RNA_substructure']
multi_cell_sems = ['G#virus', 'G#mono_cell', 'G#multi_cell', 'G#body_part', 'G#tissue']
cell_sems = ['G#cell_type', 'G#cell_component', 'G#cell_line', 'G#other_artificial_source']
other_sems = ['G#other_name']
high_level_semantic_class_names = ['amino_acid', 'nucleotide', 'multi_cell', 'cell', 'other']
high_level_semantic_class_lex_units = [genia_lexical_units, amino_acid_sems, nucleotide_sems, multi_cell_sems, cell_sems, other_sems]

# Create dictionary of lexical units and their associated semantic classes
sem = np.array(genia_lexical_units_and_sems['sem'])
lex = np.array(genia_lexical_units_and_sems['lex'])
lex_sem_dct = dict(zip(lex, sem))

# Count number of semantic classes in each high-level class
sub_class = [len(amino_acid_sems), len(nucleotide_sems), len(multi_cell_sems), len(cell_sems), len(other_sems)]

# Count number of distinct lexical units in each high-level semantic class
amino_acid = get_high_level_semantic_class_words(amino_acid_sems)
nucleotide = get_high_level_semantic_class_words(nucleotide_sems)
multi_cell = get_high_level_semantic_class_words(multi_cell_sems)
cell = get_high_level_semantic_class_words(cell_sems)
other = get_high_level_semantic_class_words(other_sems)

# Count number of lexical units used as annotations for each high-level semantic class
high_level_class_words = [genia_lexical_units, amino_acid, nucleotide, multi_cell, cell, other]
high_level_class_words_counter = [0, 0, 0, 0, 0, 0]
for i in range(len(high_level_class_words)):
  for j in range(len(vocab)):
    if vocab[j] in high_level_class_words[i]:
      high_level_class_words_counter[i] += N_i.A[0][j]

# Create dictionary of lexical units and their associated semantic classes
sem = np.array(genia_lexical_units_and_sems['sem'])
lex = np.array(genia_lexical_units_and_sems['lex'])
lex_sem_dct = dict(zip(lex, sem))

# Count number of semantic subclasses in each high-level class
subclass_counts = [len(amino_acid_sems), len(nucleotide_sems), len(multi_cell_sems), len(cell_sems), len(other_sems)]

# Gather distinct lexical units for each high-level semantic class
amino_acid = get_high_level_semantic_class_words(amino_acid_sems)
nucleotide = get_high_level_semantic_class_words(nucleotide_sems)
multi_cell = get_high_level_semantic_class_words(multi_cell_sems)
cell = get_high_level_semantic_class_words(cell_sems)
other = get_high_level_semantic_class_words(other_sems)

# Count number of lexical units used as annotations for each high-level semantic class
lex_by_semamtic_class_counts = [0, 0, 0, 0, 0, 0]
for i in range(len(high_level_semantic_class_names)):
  for j in range(len(vocab)):
    if vocab[j] in high_level_semantic_class_names[i]:
      lex_by_semamtic_class_counts[i] += N_i.A[0][j]

# Define the data
high_level_semantic_classes = ['all', 'amino_acid', 'nucleotide', 'multi_cell', 'cell', 'other']
annotations_count_zip = zip(high_level_semantic_classes, high_level_class_words_counter)
annotations_dict = dict(annotations_count_zip)
lex_unit_counts = [len(amino_acid), len(nucleotide), len(multi_cell), len(cell), len(other)]
subclass_counts = [len(amino_acid_sems), len(nucleotide_sems), len(multi_cell_sems), len(cell_sems), len(other_sems)]
annotations = [
    annotations_dict['amino_acid'],
    annotations_dict['nucleotide'],
    annotations_dict['multi_cell'],
    annotations_dict['cell'],
    annotations_dict['other']]

# Create a data frame
genia_summary_stats_df = pd.DataFrame({
    'Semantic class': ['amino_acid', 'nucleotide', 'multi_cell', 'cell', 'other'],
    'Sub-class': subclass_counts,
    'Unique terms': lex_unit_counts,
    "Annotations": annotations
})

In [10]:
# Print GENIA summary statistics
display(genia_summary_stats_df)

# Write to CSV
genia_summary_stats_df.to_csv('table-3/table-3.csv', index=False)

  Semantic class  Sub-class  Unique terms  Annotations
0     amino_acid         15         10155        42478
1     nucleotide         12          5574        11619
2     multi_cell          5          1444         5247
3           cell          4          4051        11626
4          other          1         10560        19999

## Terminology Extraction Task Experiment

Here we reproduce the result of Table 4 from the manuscript.

In [25]:
# Grab the top k terms
def top_k(dct, k):
  keys = dct.keys()
  values = []
  for key in keys:
    values.append(dct[key][:k])
  keys_values_pair = zip(keys, values)
  return dict(keys_values_pair)

# Count up terms
def count_words(lst, imp_words):
  counter = 0
  for x in lst:
    if x in imp_words:
      counter += 1
  return counter

# Randomly resort term dispersion scores data frame
def resort(term_scores_df):
  sorted_terms = []
  bursty_measure_names = term_scores_df.columns.values.tolist()[1:]

  for measure in bursty_measure_names:
      # Copy the data frame and add a random column
      temp_df = term_scores_df.copy()
      temp_df['random'] = np.random.rand(len(temp_df))
        
      # Sort by the measure and the random column
      sorted_df = temp_df[['term', measure, 'random']].sort_values(by=[measure, 'random'], ascending=[False, True])
        
      # Append the sorted terms to the list
      sorted_terms.append(np.array(sorted_df['term']))
        
      # Drop the random column from the temporary data frame
      temp_df.drop(columns='random', inplace=True)
    
  sorted_terms = np.array(sorted_terms)
  measure_term_pair = zip(bursty_measure_names, sorted_terms)
  sorted_measures = dict(measure_term_pair)
    
  return sorted_measures
    
# Calculate Precision at k scores
def calc_pk(lex_units, sorted_measures, k_values):
  measures = sorted_measures.keys()
  counts = [[], [], [], [], [], [], [], [], [], []]
  pk_dct = dict(zip(measures, counts))  
  for measure in pk_dct.keys():
      for k in k_values:
          pk_dct[measure].append(count_words(top_k(sorted_measures, k)[measure], lex_units)/k)
  result = pd.DataFrame(pk_dct, index=k_values)
  return result

# Calculate Recall at k scores
def calc_rk(lex_units, sorted_measures, k_values):
  measures = sorted_measures.keys()
  counts = [[], [], [], [], [], [], [], [], [], []]
  rk_dct = dict(zip(measures, counts))  
  for measure in rk_dct.keys():
      for k in k_values:
          rk_dct[measure].append(count_words(top_k(sorted_measures, k)[measure], lex_units)/len(lex_units))
  result = pd.DataFrame(rk_dct, index=k_values)
  return result

# Calculate F1 at k scores
def calc_fk(pk, rk):
  result = 2 * (pk * rk) / (pk + rk)
  result = result.fillna(0) # Nan scores are redefined as 0
  return result

# Calculate Rank Biased Overlap scores
def calc_rbo(sorted_measures, k_values):
  RICF = sorted_measures["RICF"]
  measures = sorted_measures.keys()
  counts = [[], [], [], [], [], [], [], [], [], []]
  rbo_dct = dict(zip(measures, counts))  
  for measure in rbo_dct.keys():
      for k in k_values:
          S = top_k(sorted_measures, k)[measure]
          T = RICF[0:k]
          rbo_dct[measure].append(rbo.RankingSimilarity(S, T).rbo())
  result = pd.DataFrame(rbo_dct, index=k_values)
  return result

# Calculate Rank Biased Overlap scores for each semantic class
def calc_rbo2(sorted_measures, categories):
  measures = sorted_measures.keys()
  counts = [[], [], [], [], [], [], [], [], [], []]
  rbo_dct = dict(zip(measures, counts))
  #rbo_dct = dict.fromkeys(measures, [])

  for measure in measures:
      l1 = sorted_measures[measure].tolist()
      
      for category, lex_units in categories.items():
          S = sorted(set(l1) & set(lex_units), key = l1.index)
          l2 = sorted_measures["RICF"].tolist()
          RICF = sorted(set(l2) & set(lex_units), key = l2.index)          
          rbo_dct[measure].append(rbo.RankingSimilarity(S, RICF).rbo()) 

  result = pd.DataFrame(rbo_dct, index=categories.keys())
  return result
    
# Calculate mean P@k, R@k, and F1@k scores
def calc_score_means(nested_list):
    result = []
    num_outer = len(nested_list)
    num_inner = len(nested_list[0])

    for i in range(num_inner):
        means = {}
        for column in nested_list[0][i].columns:
            values = [nested_list[outer][i][column].values for outer in range(num_outer)]
            mean_values = np.mean(values, axis=0)
            means[column] = mean_values
        result.append(pd.DataFrame(means, index=nested_list[0][i].index))
    return result

# Calculate standard deviations of P@k, R@k, and F1@k scores
def calc_score_sds(nested_list):
    result = []
    num_outer = len(nested_list)
    num_inner = len(nested_list[0])

    for i in range(num_inner):
        std_devs = {}
        for column in nested_list[0][i].columns:
            values = [nested_list[outer][i][column].values for outer in range(num_outer)]
            std_values = np.std(values, axis=0, ddof=1)
            std_devs[column] = std_values
        result.append(pd.DataFrame(std_devs, index=nested_list[0][i].index))
    return result

# Calculate mean RBO scores
def calc_mean_rbo_scores(scores_list):
  R = len(scores_list) # Number of replicates
  H = len(scores_list[0]) # Number of dispersion metrics
  d_metrics = scores_list[0].columns # Dispersion metrics by name
  k_values = scores_list[0].index # Top k values
  result = {}
    
  for d_metric in d_metrics:
    scores = [scores_list[r][d_metric].values for r in range(R)]
    mean_scores = np.mean(scores, axis=0)
    result[d_metric] = mean_scores
        
  return pd.DataFrame(result, index=k_values)

In [26]:
# Initialize a random seed to ensure results can be replicated
np.random.seed(641369)

# Set number of replicates
R = 100
#R = 3 # For testing purposes; change back to 100 for final results

# These are the Precision @ k, Recall @ k and Rank Biased Overlap scores
all_pk_scores = []
all_rk_scores = []
all_fk_scores = []
all_rbo_scores = []
all_rbo_scores2 = []

# Used as inputs for calculating the various scores
k_values = np.array([10, 50, 100, 500, 1000, 5000])
categories = {
    'all': genia_lexical_units,
    'amino_acid': amino_acid,
    'nucleotide': nucleotide,
    'multi_cell': multi_cell,
    'cell': cell,
    'other': other}

# Calculate evaluation metrics
for r in tqdm(range(R)):
    print('r =', r)
    pk_scores = []
    rk_scores = []
    fk_scores = []
    sorted_measures = resort(term_scores_df)
    
    for category, lex_units in categories.items():
        pk = calc_pk(lex_units, sorted_measures, k_values)
        pk_scores.append(pk)
        rk = calc_rk(lex_units, sorted_measures, k_values)
        rk_scores.append(rk)
        fk = calc_fk(pk, rk)
        fk_scores.append(fk)
    
    all_pk_scores.append(pk_scores)
    all_rk_scores.append(rk_scores)
    all_fk_scores.append(fk_scores)
    rbo_scores = calc_rbo(sorted_measures, k_values)
    all_rbo_scores.append(rbo_scores)
    rbo_scores2 = calc_rbo2(sorted_measures, categories)
    all_rbo_scores2.append(rbo_scores2)

  0%|                                                                                                                   | 0/100 [00:00<?, ?it/s]

r = 0

  1%|█                                                                                                       | 1/100 [02:36<4:18:58, 156.95s/it]

r = 1

  2%|██                                                                                                      | 2/100 [05:15<4:17:55, 157.92s/it]

r = 2

  3%|███                                                                                                     | 3/100 [07:52<4:14:43, 157.57s/it]

r = 3

  4%|████▏                                                                                                   | 4/100 [10:27<4:10:40, 156.67s/it]

r = 4

  5%|█████▏                                                                                                  | 5/100 [13:02<4:06:52, 155.93s/it]

r = 5

  6%|██████▏                                                                                                 | 6/100 [15:37<4:03:32, 155.45s/it]

r = 6

  7%|███████▎                                                                                                | 7/100 [18:11<4:00:15, 155.00s/it]

r = 7

  8%|████████▎                                                                                               | 8/100 [20:45<3:57:27, 154.87s/it]

r = 8

  9%|█████████▎                                                                                              | 9/100 [23:20<3:54:45, 154.79s/it]

r = 9

 10%|██████████▎                                                                                            | 10/100 [25:53<3:51:37, 154.41s/it]

r = 10

 11%|███████████▎                                                                                           | 11/100 [28:27<3:48:51, 154.29s/it]

r = 11

 12%|████████████▎                                                                                          | 12/100 [31:01<3:46:05, 154.16s/it]

r = 12

 13%|█████████████▍                                                                                         | 13/100 [33:37<3:44:15, 154.66s/it]

r = 13

 14%|██████████████▍                                                                                        | 14/100 [36:12<3:41:55, 154.83s/it]

r = 14

 15%|███████████████▍                                                                                       | 15/100 [38:48<3:39:40, 155.07s/it]

r = 15

 16%|████████████████▍                                                                                      | 16/100 [41:26<3:38:29, 156.07s/it]

r = 16

 17%|█████████████████▌                                                                                     | 17/100 [44:03<3:35:56, 156.10s/it]

r = 17

 18%|██████████████████▌                                                                                    | 18/100 [46:39<3:33:19, 156.09s/it]

r = 18

 19%|███████████████████▌                                                                                   | 19/100 [49:14<3:30:36, 156.01s/it]

r = 19

 20%|████████████████████▌                                                                                  | 20/100 [51:53<3:29:01, 156.77s/it]

r = 20

 21%|█████████████████████▋                                                                                 | 21/100 [54:29<3:25:58, 156.44s/it]

r = 21

 22%|██████████████████████▋                                                                                | 22/100 [57:06<3:23:44, 156.72s/it]

r = 22

 23%|███████████████████████▋                                                                               | 23/100 [59:44<3:21:34, 157.07s/it]

r = 23

 24%|████████████████████████▏                                                                            | 24/100 [1:02:22<3:19:30, 157.50s/it]

r = 24

 25%|█████████████████████████▎                                                                           | 25/100 [1:05:01<3:17:13, 157.79s/it]

r = 25

 26%|██████████████████████████▎                                                                          | 26/100 [1:07:35<3:13:23, 156.81s/it]

r = 26

 27%|███████████████████████████▎                                                                         | 27/100 [1:10:10<3:09:54, 156.09s/it]

r = 27

 28%|████████████████████████████▎                                                                        | 28/100 [1:12:45<3:06:53, 155.74s/it]

r = 28

 29%|█████████████████████████████▎                                                                       | 29/100 [1:15:23<3:05:05, 156.42s/it]

r = 29

 30%|██████████████████████████████▎                                                                      | 30/100 [1:17:59<3:02:18, 156.26s/it]

r = 30

 31%|███████████████████████████████▎                                                                     | 31/100 [1:20:38<3:00:55, 157.33s/it]

r = 31

 32%|████████████████████████████████▎                                                                    | 32/100 [1:23:23<3:00:35, 159.35s/it]

r = 32

 33%|█████████████████████████████████▎                                                                   | 33/100 [1:26:02<2:58:02, 159.45s/it]

r = 33

 34%|██████████████████████████████████▎                                                                  | 34/100 [1:28:39<2:54:33, 158.69s/it]

r = 34

 35%|███████████████████████████████████▎                                                                 | 35/100 [1:31:16<2:51:11, 158.02s/it]

r = 35

 36%|████████████████████████████████████▎                                                                | 36/100 [1:33:56<2:49:21, 158.77s/it]

r = 36

 37%|█████████████████████████████████████▎                                                               | 37/100 [1:36:34<2:46:24, 158.48s/it]

r = 37

 38%|██████████████████████████████████████▍                                                              | 38/100 [1:39:10<2:43:07, 157.86s/it]

r = 38

 39%|███████████████████████████████████████▍                                                             | 39/100 [1:41:53<2:41:55, 159.27s/it]

r = 39

 40%|████████████████████████████████████████▍                                                            | 40/100 [1:44:28<2:38:10, 158.17s/it]

r = 40

 41%|█████████████████████████████████████████▍                                                           | 41/100 [1:47:04<2:34:44, 157.36s/it]

r = 41

 42%|██████████████████████████████████████████▍                                                          | 42/100 [1:49:39<2:31:26, 156.67s/it]

r = 42

 43%|███████████████████████████████████████████▍                                                         | 43/100 [1:52:14<2:28:22, 156.19s/it]

r = 43

 44%|████████████████████████████████████████████▍                                                        | 44/100 [1:54:49<2:25:28, 155.87s/it]

r = 44

 45%|█████████████████████████████████████████████▍                                                       | 45/100 [1:57:24<2:22:33, 155.53s/it]

r = 45

 46%|██████████████████████████████████████████████▍                                                      | 46/100 [1:59:59<2:19:51, 155.41s/it]

r = 46

 47%|███████████████████████████████████████████████▍                                                     | 47/100 [2:02:34<2:17:14, 155.36s/it]

r = 47

 48%|████████████████████████████████████████████████▍                                                    | 48/100 [2:05:09<2:14:31, 155.22s/it]

r = 48

 49%|█████████████████████████████████████████████████▍                                                   | 49/100 [2:07:44<2:11:46, 155.04s/it]

r = 49

 50%|██████████████████████████████████████████████████▌                                                  | 50/100 [2:10:19<2:09:11, 155.03s/it]

r = 50

 51%|███████████████████████████████████████████████████▌                                                 | 51/100 [2:12:54<2:06:33, 154.98s/it]

r = 51

 52%|████████████████████████████████████████████████████▌                                                | 52/100 [2:15:29<2:04:03, 155.07s/it]

r = 52

 53%|█████████████████████████████████████████████████████▌                                               | 53/100 [2:18:04<2:01:21, 154.93s/it]

r = 53

 54%|██████████████████████████████████████████████████████▌                                              | 54/100 [2:20:39<1:58:52, 155.05s/it]

r = 54

 55%|███████████████████████████████████████████████████████▌                                             | 55/100 [2:23:14<1:56:15, 155.01s/it]

r = 55

 56%|████████████████████████████████████████████████████████▌                                            | 56/100 [2:25:48<1:53:35, 154.89s/it]

r = 56

 57%|█████████████████████████████████████████████████████████▌                                           | 57/100 [2:28:23<1:51:00, 154.90s/it]

r = 57

 58%|██████████████████████████████████████████████████████████▌                                          | 58/100 [2:30:58<1:48:22, 154.81s/it]

r = 58

 59%|███████████████████████████████████████████████████████████▌                                         | 59/100 [2:33:33<1:45:45, 154.77s/it]

r = 59

 60%|████████████████████████████████████████████████████████████▌                                        | 60/100 [2:36:07<1:43:11, 154.78s/it]

r = 60

 61%|█████████████████████████████████████████████████████████████▌                                       | 61/100 [2:38:47<1:41:33, 156.25s/it]

r = 61

 62%|██████████████████████████████████████████████████████████████▌                                      | 62/100 [2:41:23<1:38:49, 156.05s/it]

r = 62

 63%|███████████████████████████████████████████████████████████████▋                                     | 63/100 [2:44:02<1:36:54, 157.14s/it]

r = 63

 64%|████████████████████████████████████████████████████████████████▋                                    | 64/100 [2:46:39<1:34:11, 156.97s/it]

r = 64

 65%|█████████████████████████████████████████████████████████████████▋                                   | 65/100 [2:49:19<1:32:04, 157.85s/it]

r = 65

 66%|██████████████████████████████████████████████████████████████████▋                                  | 66/100 [2:51:59<1:29:47, 158.44s/it]

r = 66

 67%|███████████████████████████████████████████████████████████████████▋                                 | 67/100 [2:54:38<1:27:12, 158.57s/it]

r = 67

 68%|████████████████████████████████████████████████████████████████████▋                                | 68/100 [2:57:13<1:24:04, 157.65s/it]

r = 68

 69%|█████████████████████████████████████████████████████████████████████▋                               | 69/100 [2:59:48<1:21:04, 156.91s/it]

r = 69

 70%|██████████████████████████████████████████████████████████████████████▋                              | 70/100 [3:02:28<1:18:54, 157.82s/it]

r = 70

 71%|███████████████████████████████████████████████████████████████████████▋                             | 71/100 [3:05:05<1:16:10, 157.61s/it]

r = 71

 72%|████████████████████████████████████████████████████████████████████████▋                            | 72/100 [3:07:41<1:13:16, 157.00s/it]

r = 72

 73%|█████████████████████████████████████████████████████████████████████████▋                           | 73/100 [3:10:16<1:10:27, 156.58s/it]

r = 73

 74%|██████████████████████████████████████████████████████████████████████████▋                          | 74/100 [3:12:52<1:07:43, 156.29s/it]

r = 74

 75%|███████████████████████████████████████████████████████████████████████████▊                         | 75/100 [3:15:27<1:05:00, 156.01s/it]

r = 75

 76%|████████████████████████████████████████████████████████████████████████████▊                        | 76/100 [3:18:03<1:02:18, 155.79s/it]

r = 76

 77%|███████████████████████████████████████████████████████████████████████████████▎                       | 77/100 [3:20:41<59:58, 156.46s/it]

r = 77

 78%|████████████████████████████████████████████████████████████████████████████████▎                      | 78/100 [3:23:19<57:30, 156.86s/it]

r = 78

 79%|█████████████████████████████████████████████████████████████████████████████████▎                     | 79/100 [3:25:55<54:54, 156.87s/it]

r = 79

 80%|██████████████████████████████████████████████████████████████████████████████████▍                    | 80/100 [3:28:32<52:18, 156.92s/it]

r = 80

 81%|███████████████████████████████████████████████████████████████████████████████████▍                   | 81/100 [3:31:10<49:46, 157.18s/it]

r = 81

 82%|████████████████████████████████████████████████████████████████████████████████████▍                  | 82/100 [3:33:48<47:12, 157.34s/it]

r = 82

 83%|█████████████████████████████████████████████████████████████████████████████████████▍                 | 83/100 [3:36:23<44:21, 156.58s/it]

r = 83

 84%|██████████████████████████████████████████████████████████████████████████████████████▌                | 84/100 [3:39:01<41:50, 156.93s/it]

r = 84

 85%|███████████████████████████████████████████████████████████████████████████████████████▌               | 85/100 [3:41:37<39:13, 156.89s/it]

r = 85

 86%|████████████████████████████████████████████████████████████████████████████████████████▌              | 86/100 [3:44:15<36:38, 157.05s/it]

r = 86

 87%|█████████████████████████████████████████████████████████████████████████████████████████▌             | 87/100 [3:46:54<34:10, 157.76s/it]

r = 87

 88%|██████████████████████████████████████████████████████████████████████████████████████████▋            | 88/100 [3:49:33<31:36, 158.00s/it]

r = 88

 89%|███████████████████████████████████████████████████████████████████████████████████████████▋           | 89/100 [3:52:11<28:58, 158.06s/it]

r = 89

 90%|████████████████████████████████████████████████████████████████████████████████████████████▋          | 90/100 [3:54:48<26:17, 157.77s/it]

r = 90

 91%|█████████████████████████████████████████████████████████████████████████████████████████████▋         | 91/100 [3:57:25<23:38, 157.63s/it]

r = 91

 92%|██████████████████████████████████████████████████████████████████████████████████████████████▊        | 92/100 [4:00:01<20:55, 156.95s/it]

r = 92

 93%|███████████████████████████████████████████████████████████████████████████████████████████████▊       | 93/100 [4:02:36<18:15, 156.43s/it]

r = 93

 94%|████████████████████████████████████████████████████████████████████████████████████████████████▊      | 94/100 [4:05:11<15:37, 156.17s/it]

r = 94

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████▊     | 95/100 [4:07:47<13:00, 156.03s/it]

r = 95

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████▉    | 96/100 [4:10:22<10:23, 155.80s/it]

r = 96

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████▉   | 97/100 [4:12:58<07:46, 155.63s/it]

r = 97

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 98/100 [4:15:33<05:10, 155.48s/it]

r = 98

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 99/100 [4:18:08<02:35, 155.29s/it]

r = 99

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [4:20:43<00:00, 156.43s/it]

Save evaluation metrics as Pkl files.

In [27]:
# Ensure the directory exists
os.makedirs('scores-dump', exist_ok=True)

# Write P@k scores to Pkl
with open('scores-dump/all_pk_scores.pkl', 'wb') as file:
    pickle.dump(all_pk_scores, file)

# Write R@k scores to Pkl
with open('scores-dump/all_rk_scores.pkl', 'wb') as file:
    pickle.dump(all_rk_scores, file)

# Write F1@k scores to Pkl
with open('scores-dump/all_fk_scores.pkl', 'wb') as file:
    pickle.dump(all_fk_scores, file)

# Write RBO scores to Pkl
with open('scores-dump/all_rbo_scores.pkl', 'wb') as file:
    pickle.dump(all_rbo_scores, file)

# Write RBO scores as calculated for each semantic class to Pkl
with open('scores-dump/all_rbo_scores2.pkl', 'wb') as file:
    pickle.dump(all_rbo_scores2, file)

In [28]:
# Calculate mean P@k scores and write to CSV
all_pk_scores_means = calc_score_means(all_pk_scores)
pd.DataFrame(all_pk_scores_means[0]).to_csv('table-4/table-4-all-pk-means.csv', index=False)
pd.DataFrame(all_pk_scores_means[1]).to_csv('table-4/table-4-amino_acid-pk-means.csv', index=False)
pd.DataFrame(all_pk_scores_means[2]).to_csv('table-4/table-4-nucleotide-pk-means.csv', index=False)
pd.DataFrame(all_pk_scores_means[3]).to_csv('table-4/table-4-multicell-pk-means.csv', index=False)
pd.DataFrame(all_pk_scores_means[4]).to_csv('table-4/table-4-cell-pk-means.csv', index=False)
pd.DataFrame(all_pk_scores_means[5]).to_csv('table-4/table-4-other-pk-means.csv', index=False)

# Calculate standard deviations for P@k scores and write to CSV
all_pk_scores_sds = calc_score_sds(all_pk_scores)
pd.DataFrame(all_pk_scores_sds[0]).to_csv('table-4/table-4-all-pk-sds.csv', index=False)
pd.DataFrame(all_pk_scores_sds[1]).to_csv('table-4/table-4-amino_acid-pk-sds.csv', index=False)
pd.DataFrame(all_pk_scores_sds[2]).to_csv('table-4/table-4-nucleotide-pk-sds.csv', index=False)
pd.DataFrame(all_pk_scores_sds[3]).to_csv('table-4/table-4-multicell-pk-sds.csv', index=False)
pd.DataFrame(all_pk_scores_sds[4]).to_csv('table-4/table-4-cell-pk-sds.csv', index=False)
pd.DataFrame(all_pk_scores_sds[5]).to_csv('table-4/table-4-other-pk-sds.csv', index=False)

In [29]:
# Display mean P@k scores and console
print("Mean P@k scores:")
with pd.option_context('display.precision', 4):
    display(all_pk_scores_means[0].round(4))
    display(all_pk_scores_means[1].round(4))
    display(all_pk_scores_means[2].round(4))
    display(all_pk_scores_means[3].round(4))
    display(all_pk_scores_means[4].round(4))
    display(all_pk_scores_means[5].round(4))

Mean P@k scores:

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.8550  0.8180  0.9520  1.0000  1.0000  0.9000  1.0000
50    0.8582  0.8506  0.9540  0.9600  1.0000  0.7714  1.0000
100   0.8630  0.8498  0.9537  0.9800  0.9800  0.7800  1.0000
500   0.8611  0.8480  0.9527  0.9834  0.9740  0.8252  0.9916
1000  0.8592  0.8502  0.9528  0.9813  0.9635  0.8537  0.9854
5000  0.8601  0.8503  0.9150  0.9280  0.8973  0.8753  0.9315

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.2550  0.2470  0.5620  1.0000  0.8000  0.1690  1.0000
50    0.2654  0.2422  0.5312  0.7552  0.7000  0.2154  0.7902
100   0.2636  0.2418  0.5397  0.8200  0.7448  0.1316  0.8300
500   0.2652  0.2440  0.5384  0.6878  0.6220  0.2200  0.6920
1000  0.2652  0.2457  0.5379  0.6443  0.5901  0.2528  0.6435
5000  0.2651  0.2468  0.4293  0.4282  0.4109  0.2801  0.4294

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.1560  0.1420  0.1460  0.0000  0.1000  0.0000  0.0000
50    0.1576  0.1520  0.1542  0.1000  0.1200  0.1200  0.1000
100   0.1592  0.1559  0.1477  0.1000  0.1000  0.1444  0.1100
500   0.1563  0.1538  0.1521  0.1418  0.1460  0.1363  0.1426
1000  0.1557  0.1534  0.1527  0.1347  0.1395  0.1401  0.1364
5000  0.1556  0.1547  0.1527  0.1553  0.1483  0.1528  0.1557

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0400  0.0220  0.0420  0.0000  0.0000  0.0000  0.0000
50    0.0358  0.0310  0.0406  0.0400  0.0400  0.0800  0.0400
100   0.0358  0.0337  0.0427  0.0200  0.0200  0.0900  0.0200
500   0.0349  0.0359  0.0416  0.0334  0.0320  0.0561  0.0336
1000  0.0361  0.0361  0.0411  0.0368  0.0420  0.0530  0.0358
5000  0.0371  0.0358  0.0438  0.0439  0.0413  0.0468  0.0441

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.1190  0.1000  0.0620  0.0000  0.0000  0.0700  0.0000
50    0.1172  0.1136  0.0806  0.0048  0.0000  0.1560  0.0098
100   0.1113  0.1099  0.0821  0.0100  0.0200  0.1200  0.0100
500   0.1113  0.1107  0.0816  0.0390  0.0600  0.0900  0.0399
1000  0.1101  0.1111  0.0819  0.0597  0.0689  0.0920  0.0598
5000  0.1105  0.1104  0.0956  0.1002  0.0987  0.0947  0.1006

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.2850  0.3070  0.1400  0.0000  0.1000  0.6610  0.0000
50    0.2822  0.3118  0.1474  0.0600  0.1400  0.2000  0.0600
100   0.2931  0.3085  0.1415  0.0300  0.0952  0.2940  0.0300
500   0.2933  0.3036  0.1389  0.0815  0.1140  0.3228  0.0834
1000  0.2920  0.3039  0.1392  0.1058  0.1229  0.3158  0.1100
5000  0.2918  0.3026  0.1937  0.2004  0.1981  0.3010  0.2016

In [30]:
# Displaye standard deviation of P@k scores to console
print("P@k scores standard deviations:")
with pd.option_context('display.precision', 4):
    display(all_pk_scores_sds[0].round(4))
    display(all_pk_scores_sds[1].round(4))
    display(all_pk_scores_sds[2].round(4))
    display(all_pk_scores_sds[3].round(4))
    display(all_pk_scores_sds[4].round(4))
    display(all_pk_scores_sds[5].round(4))

P@k scores standard deviations:

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.1077  0.1192  0.0717  0.0000  0.0000  0.0000  0.0000
50    0.0537  0.0462  0.0318  0.0000  0.0000  0.0100  0.0000
100   0.0342  0.0331  0.0207  0.0000  0.0000  0.0000  0.0000
500   0.0159  0.0145  0.0080  0.0010  0.0000  0.0010  0.0009
1000  0.0114  0.0110  0.0049  0.0018  0.0011  0.0005  0.0014
5000  0.0042  0.0042  0.0006  0.0007  0.0001  0.0001  0.0003

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.1452  0.1352  0.1536  0.0000  0.0000  0.0465  0.0000
50    0.0678  0.0553  0.0707  0.0086  0.0000  0.0085  0.0100
100   0.0458  0.0378  0.0463  0.0000  0.0050  0.0037  0.0000
500   0.0195  0.0191  0.0202  0.0044  0.0000  0.0000  0.0042
1000  0.0123  0.0131  0.0120  0.0049  0.0007  0.0006  0.0039
5000  0.0053  0.0057  0.0010  0.0011  0.0002  0.0002  0.0005

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.1008  0.1148  0.1105  0.0000  0.0000  0.0000  0.0000
50    0.0530  0.0431  0.0501  0.0000  0.0000  0.0000  0.0000
100   0.0361  0.0357  0.0372  0.0000  0.0000  0.0050  0.0000
500   0.0159  0.0158  0.0156  0.0027  0.0000  0.0007  0.0028
1000  0.0107  0.0113  0.0089  0.0032  0.0005  0.0007  0.0028
5000  0.0046  0.0040  0.0008  0.0008  0.0001  0.0002  0.0003

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0569  0.0440  0.0572  0.0000  0.0000  0.0000  0.0000
50    0.0270  0.0247  0.0273  0.0000  0.0000  0.0000  0.0000
100   0.0192  0.0186  0.0164  0.0000  0.0000  0.0000  0.0000
500   0.0075  0.0075  0.0083  0.0015  0.0000  0.0005  0.0017
1000  0.0053  0.0053  0.0052  0.0018  0.0007  0.0000  0.0013
5000  0.0022  0.0023  0.0005  0.0005  0.0001  0.0000  0.0003

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0950  0.0985  0.0776  0.0000  0.0000  0.0461  0.0000
50    0.0409  0.0461  0.0420  0.0086  0.0000  0.0080  0.0100
100   0.0264  0.0342  0.0295  0.0000  0.0000  0.0000  0.0000
500   0.0155  0.0138  0.0107  0.0022  0.0000  0.0000  0.0025
1000  0.0102  0.0096  0.0069  0.0025  0.0007  0.0000  0.0018
5000  0.0044  0.0037  0.0005  0.0007  0.0001  0.0001  0.0004

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.1438  0.1423  0.1044  0.0000  0.0000  0.0549  0.0000
50    0.0632  0.0673  0.0471  0.0000  0.0000  0.0000  0.0000
100   0.0438  0.0493  0.0317  0.0000  0.0050  0.0049  0.0000
500   0.0190  0.0200  0.0135  0.0024  0.0000  0.0010  0.0027
1000  0.0122  0.0140  0.0086  0.0036  0.0006  0.0007  0.0029
5000  0.0051  0.0062  0.0010  0.0011  0.0002  0.0002  0.0004

In [31]:
# Calculate mean R@k scores and write to CSV
all_rk_scores_means = calc_score_means(all_rk_scores)
pd.DataFrame(all_rk_scores_means[0]).to_csv('table-4/table-4-all-rk-means.csv', index=False)
pd.DataFrame(all_rk_scores_means[1]).to_csv('table-4/table-4-amino_acid-rk-means.csv', index=False)
pd.DataFrame(all_rk_scores_means[2]).to_csv('table-4/table-4-nucleotide-rk-means.csv', index=False)
pd.DataFrame(all_rk_scores_means[3]).to_csv('table-4/table-4-multicell-rk-means.csv', index=False)
pd.DataFrame(all_rk_scores_means[4]).to_csv('table-4/table-4-cell-rk-means.csv', index=False)
pd.DataFrame(all_rk_scores_means[5]).to_csv('table-4/table-4-other-rk-means.csv', index=False)

# Calculate standard deviations for R@k scores and write to CSV
all_rk_scores_sds = calc_score_sds(all_rk_scores)
pd.DataFrame(all_rk_scores_sds[0]).to_csv('table-4/table-4-all-rk-sds.csv', index=False)
pd.DataFrame(all_rk_scores_sds[1]).to_csv('table-4/table-4-amino_acid-rk-sds.csv', index=False)
pd.DataFrame(all_rk_scores_sds[2]).to_csv('table-4/table-4-nucleotide-rk-sds.csv', index=False)
pd.DataFrame(all_rk_scores_sds[3]).to_csv('table-4/table-4-multicell-rk-sds.csv', index=False)
pd.DataFrame(all_rk_scores_sds[4]).to_csv('table-4/table-4-cell-rk-sds.csv', index=False)
pd.DataFrame(all_rk_scores_sds[5]).to_csv('table-4/table-4-other-rk-sds.csv', index=False)

In [32]:
# Display mean R@k scores console
print("Mean R@k scores:")
with pd.option_context('display.precision', 4):
    display(all_rk_scores_means[0].round(4))
    display(all_rk_scores_means[1].round(4))
    display(all_rk_scores_means[2].round(4))
    display(all_rk_scores_means[3].round(4))
    display(all_rk_scores_means[4].round(4))
    display(all_rk_scores_means[5].round(4))

Mean R@k scores:

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0003  0.0003  0.0003  0.0003  0.0003  0.0003  0.0003
50    0.0013  0.0013  0.0015  0.0015  0.0016  0.0012  0.0016
100   0.0027  0.0027  0.0030  0.0031  0.0031  0.0025  0.0031
500   0.0135  0.0133  0.0150  0.0155  0.0153  0.0130  0.0156
1000  0.0270  0.0267  0.0300  0.0309  0.0303  0.0269  0.0310
5000  0.1353  0.1338  0.1439  0.1460  0.1411  0.1377  0.1465

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0003  0.0002  0.0006  0.0010  0.0008  0.0002  0.0010
50    0.0013  0.0012  0.0026  0.0037  0.0034  0.0011  0.0039
100   0.0026  0.0024  0.0053  0.0081  0.0073  0.0013  0.0082
500   0.0131  0.0120  0.0265  0.0339  0.0306  0.0108  0.0341
1000  0.0261  0.0242  0.0530  0.0634  0.0581  0.0249  0.0634
5000  0.1305  0.1215  0.2114  0.2109  0.2023  0.1379  0.2114

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0003  0.0003  0.0003  0.0000  0.0002  0.0000  0.0000
50    0.0014  0.0014  0.0014  0.0009  0.0011  0.0011  0.0009
100   0.0029  0.0028  0.0026  0.0018  0.0018  0.0026  0.0020
500   0.0140  0.0138  0.0136  0.0127  0.0131  0.0122  0.0128
1000  0.0279  0.0275  0.0274  0.0242  0.0250  0.0251  0.0245
5000  0.1396  0.1388  0.1370  0.1393  0.1330  0.1370  0.1397

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0003  0.0002  0.0003  0.0000  0.0000  0.0000  0.0000
50    0.0012  0.0011  0.0014  0.0014  0.0014  0.0028  0.0014
100   0.0025  0.0023  0.0030  0.0014  0.0014  0.0062  0.0014
500   0.0121  0.0124  0.0144  0.0116  0.0111  0.0194  0.0116
1000  0.0250  0.0250  0.0284  0.0255  0.0291  0.0367  0.0248
5000  0.1285  0.1240  0.1516  0.1519  0.1429  0.1620  0.1527

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0003  0.0002  0.0002  0.0000  0.0000  0.0002  0.0000
50    0.0014  0.0014  0.0010  0.0001  0.0000  0.0019  0.0001
100   0.0027  0.0027  0.0020  0.0002  0.0005  0.0030  0.0002
500   0.0137  0.0137  0.0101  0.0048  0.0074  0.0111  0.0049
1000  0.0272  0.0274  0.0202  0.0147  0.0170  0.0227  0.0148
5000  0.1364  0.1363  0.1180  0.1237  0.1219  0.1168  0.1242

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0003  0.0003  0.0001  0.0000  0.0001  0.0006  0.0000
50    0.0013  0.0015  0.0007  0.0003  0.0007  0.0009  0.0003
100   0.0028  0.0029  0.0013  0.0003  0.0009  0.0028  0.0003
500   0.0139  0.0144  0.0066  0.0039  0.0054  0.0153  0.0039
1000  0.0277  0.0288  0.0132  0.0100  0.0116  0.0299  0.0104
5000  0.1382  0.1433  0.0917  0.0949  0.0938  0.1425  0.0954

In [78]:
# Display standard deviation of R@k scores to console
print("R@k scores standard deviations:")
with pd.option_context('display.precision', 4):
    display(all_rk_scores_sds[0].round(4))
    display(all_rk_scores_sds[1].round(4))
    display(all_rk_scores_sds[2].round(4))
    display(all_rk_scores_sds[3].round(4))
    display(all_rk_scores_sds[4].round(4))
    display(all_rk_scores_sds[5].round(4))

R@k scores standard deviations:

         IDF     ICF  Chi-sq      CG  ICB  DoP    RICF
10    0.0000  0.0000  0.0000  0.0000  0.0  0.0  0.0000
50    0.0001  0.0001  0.0001  0.0000  0.0  0.0  0.0000
100   0.0001  0.0001  0.0001  0.0000  0.0  0.0  0.0000
500   0.0003  0.0002  0.0001  0.0000  0.0  0.0  0.0000
1000  0.0004  0.0003  0.0002  0.0001  0.0  0.0  0.0000
5000  0.0007  0.0007  0.0001  0.0001  0.0  0.0  0.0001

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0001  0.0001  0.0002  0.0000  0.0000  0.0000  0.0000
50    0.0003  0.0003  0.0003  0.0000  0.0000  0.0000  0.0000
100   0.0005  0.0004  0.0005  0.0000  0.0000  0.0000  0.0000
500   0.0010  0.0009  0.0010  0.0002  0.0000  0.0000  0.0002
1000  0.0012  0.0013  0.0012  0.0005  0.0001  0.0001  0.0004
5000  0.0026  0.0028  0.0005  0.0005  0.0001  0.0001  0.0003

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0002  0.0002  0.0002  0.0000  0.0000  0.0000  0.0000
50    0.0005  0.0004  0.0004  0.0000  0.0000  0.0000  0.0000
100   0.0006  0.0006  0.0007  0.0000  0.0000  0.0001  0.0000
500   0.0014  0.0014  0.0014  0.0002  0.0000  0.0001  0.0003
1000  0.0019  0.0020  0.0016  0.0006  0.0001  0.0001  0.0005
5000  0.0042  0.0036  0.0007  0.0007  0.0001  0.0002  0.0003

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0004  0.0003  0.0004  0.0000  0.0000  0.0000  0.0000
50    0.0009  0.0009  0.0009  0.0000  0.0000  0.0000  0.0000
100   0.0013  0.0013  0.0011  0.0000  0.0000  0.0000  0.0000
500   0.0026  0.0026  0.0029  0.0005  0.0000  0.0002  0.0006
1000  0.0037  0.0037  0.0036  0.0013  0.0005  0.0000  0.0009
5000  0.0076  0.0080  0.0017  0.0018  0.0003  0.0000  0.0009

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0002  0.0002  0.0002  0.0000  0.0000  0.0001  0.0000
50    0.0005  0.0006  0.0005  0.0001  0.0000  0.0001  0.0001
100   0.0007  0.0008  0.0007  0.0000  0.0000  0.0000  0.0000
500   0.0019  0.0017  0.0013  0.0003  0.0000  0.0000  0.0003
1000  0.0025  0.0024  0.0017  0.0006  0.0002  0.0000  0.0004
5000  0.0054  0.0046  0.0007  0.0009  0.0002  0.0001  0.0004

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0001  0.0001  0.0001  0.0000  0.0000  0.0001  0.0000
50    0.0003  0.0003  0.0002  0.0000  0.0000  0.0000  0.0000
100   0.0004  0.0005  0.0003  0.0000  0.0000  0.0000  0.0000
500   0.0009  0.0009  0.0006  0.0001  0.0000  0.0000  0.0001
1000  0.0012  0.0013  0.0008  0.0003  0.0001  0.0001  0.0003
5000  0.0024  0.0030  0.0005  0.0005  0.0001  0.0001  0.0002

In [65]:
# Calculate mean F1@k scores and write to CSV
all_fk_scores_means = calc_score_means(all_fk_scores)
pd.DataFrame(all_fk_scores_means[0]).to_csv('table-4/table-4-all-fk-means.csv', index=False)
pd.DataFrame(all_fk_scores_means[1]).to_csv('table-4/table-4-amino_acid-fk-means.csv', index=False)
pd.DataFrame(all_fk_scores_means[2]).to_csv('table-4/table-4-nucleotide-fk-means.csv', index=False)
pd.DataFrame(all_fk_scores_means[3]).to_csv('table-4/table-4-multicell-fk-means.csv', index=False)
pd.DataFrame(all_fk_scores_means[4]).to_csv('table-4/table-4-cell-fk-means.csv', index=False)
pd.DataFrame(all_fk_scores_means[5]).to_csv('table-4/table-4-other-fk-means.csv', index=False)

# Calculate standard deviations for F1@k scores and write to CSV
all_fk_scores_sds = calc_score_sds(all_fk_scores)
pd.DataFrame(all_fk_scores_sds[0]).to_csv('table-4/table-4-all-fk-sds.csv', index=False)
pd.DataFrame(all_fk_scores_sds[1]).to_csv('table-4/table-4-amino_acid-fk-sds.csv', index=False)
pd.DataFrame(all_fk_scores_sds[2]).to_csv('table-4/table-4-nucleotide-fk-sds.csv', index=False)
pd.DataFrame(all_fk_scores_sds[3]).to_csv('table-4/table-4-multicell-fk-sds.csv', index=False)
pd.DataFrame(all_fk_scores_sds[4]).to_csv('table-4/table-4-cell-fk-sds.csv', index=False)
pd.DataFrame(all_fk_scores_sds[5]).to_csv('table-4/table-4-other-fk-sds.csv', index=False)

In [33]:
# Display mean F1@k scores to console
print("Mean F1@k scores:")
with pd.option_context('display.precision', 4):
    display(all_fk_scores_means[0].round(4))
    display(all_fk_scores_means[1].round(4))
    display(all_fk_scores_means[2].round(4))
    display(all_fk_scores_means[3].round(4))
    display(all_fk_scores_means[4].round(4))
    display(all_fk_scores_means[5].round(4))

Mean F1@k scores:

NameError: name 'all_fk_scores_means' is not defined

In [75]:
# Display standard deviation of F1@k scores to console
print("F1@k scores standard deviations:")
with pd.option_context('display.precision', 4):
    display(all_fk_scores_sds[0].round(4))
    display(all_fk_scores_sds[1].round(4))
    display(all_fk_scores_sds[2].round(4))
    display(all_fk_scores_sds[3].round(4))
    display(all_fk_scores_sds[4].round(4))
    display(all_fk_scores_sds[5].round(4))

F1@k scores standard deviations:

         IDF     ICF  Chi-sq      CG     ICB  DoP    RICF
10    0.0001  0.0001  0.0000  0.0000  0.0000  0.0  0.0000
50    0.0002  0.0001  0.0001  0.0000  0.0000  0.0  0.0000
100   0.0002  0.0002  0.0001  0.0000  0.0000  0.0  0.0000
500   0.0005  0.0004  0.0002  0.0000  0.0000  0.0  0.0000
1000  0.0007  0.0007  0.0003  0.0001  0.0001  0.0  0.0001
5000  0.0011  0.0011  0.0002  0.0002  0.0000  0.0  0.0001

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0003  0.0003  0.0003  0.0000  0.0000  0.0001  0.0000
50    0.0007  0.0005  0.0007  0.0001  0.0000  0.0001  0.0001
100   0.0009  0.0007  0.0009  0.0000  0.0001  0.0001  0.0000
500   0.0018  0.0018  0.0019  0.0004  0.0000  0.0000  0.0004
1000  0.0022  0.0023  0.0022  0.0009  0.0001  0.0001  0.0007
5000  0.0035  0.0038  0.0006  0.0007  0.0002  0.0001  0.0003

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0004  0.0004  0.0004  0.0000  0.0000  0.0000  0.0000
50    0.0009  0.0008  0.0009  0.0000  0.0000  0.0000  0.0000
100   0.0013  0.0013  0.0013  0.0000  0.0000  0.0002  0.0000
500   0.0026  0.0026  0.0026  0.0004  0.0000  0.0001  0.0005
1000  0.0033  0.0034  0.0027  0.0010  0.0002  0.0002  0.0009
5000  0.0044  0.0038  0.0007  0.0007  0.0001  0.0002  0.0003

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0008  0.0006  0.0008  0.0000  0.0000  0.0000  0.0000
50    0.0018  0.0017  0.0018  0.0000  0.0000  0.0000  0.0000
100   0.0025  0.0024  0.0021  0.0000  0.0000  0.0000  0.0000
500   0.0039  0.0039  0.0043  0.0008  0.0000  0.0003  0.0009
1000  0.0044  0.0043  0.0042  0.0015  0.0005  0.0000  0.0011
5000  0.0034  0.0036  0.0008  0.0008  0.0002  0.0000  0.0004

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0005  0.0005  0.0004  0.0000  0.0000  0.0002  0.0000
50    0.0010  0.0011  0.0010  0.0002  0.0000  0.0002  0.0002
100   0.0013  0.0016  0.0014  0.0000  0.0000  0.0000  0.0000
500   0.0034  0.0030  0.0024  0.0005  0.0000  0.0000  0.0006
1000  0.0040  0.0038  0.0027  0.0010  0.0003  0.0000  0.0007
5000  0.0049  0.0041  0.0006  0.0008  0.0002  0.0001  0.0004

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF
10    0.0003  0.0003  0.0002  0.0000  0.0000  0.0001  0.0000
50    0.0006  0.0006  0.0004  0.0000  0.0000  0.0000  0.0000
100   0.0008  0.0009  0.0006  0.0000  0.0001  0.0001  0.0000
500   0.0017  0.0018  0.0012  0.0002  0.0000  0.0001  0.0002
1000  0.0021  0.0024  0.0015  0.0006  0.0001  0.0001  0.0005
5000  0.0033  0.0040  0.0006  0.0007  0.0002  0.0001  0.0003

In [34]:
# Calculate mean RBO scores and display to console
mean_rbo_scores = calc_mean_rbo_scores(all_rbo_scores)
  
with pd.option_context('display.precision', 4):
    display(mean_rbo_scores.round(4))

         IDF  ICF  Chi-sq      CG     ICB     DoP  RICF
10    0.0000  0.0  0.0010  0.9123  0.6134  0.0000   1.0
50    0.0003  0.0  0.0084  0.8988  0.6886  0.0000   1.0
100   0.0010  0.0  0.0186  0.9078  0.7028  0.0000   1.0
500   0.0068  0.0  0.0993  0.9309  0.7288  0.0005   1.0
1000  0.0125  0.0  0.1985  0.9354  0.7656  0.0031   1.0
5000  0.0603  0.0  0.6531  0.9066  0.7956  0.0431   1.0

In [35]:
# Calculate mean RBO scores by semantic class and display to console
mean_rbo_scores2 = calc_mean_rbo_scores(all_rbo_scores2)
  
with pd.option_context('display.precision', 4):
    display(mean_rbo_scores2.round(4))

               IDF     ICF  Chi-sq      CG     ICB     DoP  RICF
all         0.4989  0.4268  0.7823  0.7932  0.7487  0.4905   1.0
amino_acid  0.4832  0.3866  0.7978  0.8416  0.7961  0.4728   1.0
nucleotide  0.5036  0.4322  0.7708  0.7788  0.7402  0.4919   1.0
multi_cell  0.4969  0.4163  0.8047  0.8102  0.7539  0.4880   1.0
cell        0.5008  0.4359  0.7788  0.7775  0.7304  0.4922   1.0
other       0.5138  0.4636  0.7556  0.7402  0.6935  0.5079   1.0

## Top 10 Ranked Terms Example

Here we reproduce the result of Table 5 from the manuscript.

In [23]:
# Initialize a random seed to ensure results can be replicated
np.random.seed(641369)

In [ ]:
ranked_terms_df = resort(term_scores_df)
top_10_ranked_terms_df = pd.DataFrame(top_k(ranked_terms_df, 10))
display(top_10_ranked_terms_df)

In [25]:
# Write to CSV
top_10_ranked_terms_df.to_csv('table-5/table-5.csv', index=False)

## Stopwords Exploratory Analysis

Here we reproduce the result of Table 6 from the manuscript.

In [ ]:
import pandas as pd
from nltk.corpus import stopwords

# Ensure you have the stopwords downloaded
import nltk
nltk.download('stopwords')

def getrank(sorted_measures):
    unique_terms = set()
    for terms in sorted_measures.values():
        unique_terms.update(terms)
    unique_terms = sorted(unique_terms)
    
    # Create a data frame to hold the rankings
    ranking_df = pd.DataFrame(index=unique_terms, columns=sorted_measures.keys())
    
    # Fill the data frame with rankings
    for measure, terms in sorted_measures.items():
        for rank, term in enumerate(terms):
            ranking_df.at[term, measure] = rank + 1  # Rank starts from 1
    
    # Replace NaN with a large number to indicate unranked terms
    ranking_df = ranking_df.fillna(len(unique_terms) + 1)
    #csv_file_path = 'ranking_table.csv'
    #ranking_df.to_csv(csv_file_path)
    return ranking_df

# Function to filter stopwords from the ranking data frame
def filter_stopwords(ranking_df):
    stopwords_list = set(stopwords.words('english'))
    
    # Filter the data frame to include only stopwords
    stopwords_rank = ranking_df[ranking_df.index.isin(stopwords_list)]
    
    # Save the stopwords ranking data frame to a CSV file
    #csv_file_path = 'stopwords_ranking_table.csv'
    #stopwords_rank.to_csv(csv_file_path)
    
    return stopwords_rank

In [ ]:
# Initialize a random seed to ensure results can be replicated
np.random.seed(641369)

# Generate term dispersion ranks for R different versions of the data
R = 100
all_quantiles_df = []
for r in tqdm(range(R)):
    sorted_measures = resort(term_scores_df)
    rank = getrank(sorted_measures)
    stopwords_ranks_df = filter_stopwords(rank)
    bursty_measure_names = stopwords_ranks_df.head(0)
    quantiles = []
    for bursty_measure_name in bursty_measure_names:
        quantiles.append(stopwords_ranks_df[bursty_measure_name].quantile([0, 0.25, 0.5, 0.75, 1]))
    quantiles_df = pd.DataFrame(quantiles)
    all_quantiles_df.append(quantiles_df)

In [28]:
# Extract the column and index names from the first quantiles data frame
columns = all_quantiles_df[0].columns
index = all_quantiles_df[0].index

# Initialize empty data frames to store the mean and standard deviation values
mean_df = pd.DataFrame(index=index, columns=columns)
std_df = pd.DataFrame(index=index, columns=columns)

# Compute the mean and standard deviation of corresponding elements across all matrices
for col in columns:
    for idx in index:
        values = [matrix.at[idx, col] for matrix in all_quantiles_df]
        mean_df.at[idx, col] = np.mean(values)
        std_df.at[idx, col] = np.std(values)

In [ ]:
# Display the resulting data frames
print("Mean values:")
with pd.option_context('display.precision', 4):
    display(mean_df)
print("\nStandard deviations:")
with pd.option_context('display.precision', 4):
    display(std_df)

In [30]:
# Write to CSV
mean_df.to_csv('table-6/table-6-means.csv')
std_df.to_csv('table-6/table-6-sds.csv')